// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.StageMessage
{
    //MSGTYPE_DECLARE(MSG_REQUEST_STAGE_REAP_REWARD),
    // 请求领取阶段性奖励
    public sealed class RequestReapStageReward : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_STAGE_REAP_REWARD;
        public short GetMsgType { get { return MsgType; } }
        public uint Stage;// 请求领取的STAEG ID（类型*100+阶段）
        public byte isShow;// 是否展示
        
        public static void Send(uint stage, byte isShow, object className)
        {
            var packet = new RequestReapStageReward
            {
                Stage = stage,
                isShow = isShow
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            Stage = reader.ReadUInt32();
            isShow = reader.ReadByte();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(Stage);
            writer.Write(isShow);
        }
    }
}
