// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.FriendMessage
{
    //通知邀请道具过期
    public sealed class NotifyInviteGiftInviteInfoMessage : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_INVITE_GIFT_INVITE_INFO;
        public short GetMsgType { get { return MsgType; } }
        public InviteGiftInviteInfo[] infoVec;//邀请信息
        
        public static void Send(InviteGiftInviteInfo[] infoVec, object className)
        {
            var packet = new NotifyInviteGiftInviteInfoMessage
            {
                infoVec = infoVec
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            var length1 = reader.ReadUInt16();
            infoVec = new InviteGiftInviteInfo[length1];
            for (var i1 = 0; i1 < length1; i1++)
            {
                infoVec[i1] = new InviteGiftInviteInfo();
                infoVec[i1].ReadFromStream(reader);
            }
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            ushort count1 = (ushort)(infoVec == null ? 0 : infoVec.Length);
            writer.Write(count1);
            for(var i1 = 0; i1 < count1; i1++)
            {
                infoVec[i1].WriteToStream(writer);
            }
        }
    }
}
