// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

using GameProtocol.BulkDataType;
namespace GameProtocol.FriendMessage
{
    //通知邀请好礼玩家信息
    public sealed class NotifyInviteGiftPlayerInfoMessage : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_INVITE_GIFT_PLAYER_INFO;
        public short GetMsgType { get { return MsgType; } }
        public InviteGiftPlayerInfo[] charInfoVec;//玩家信息
        
        public static void Send(InviteGiftPlayerInfo[] charInfoVec, object className)
        {
            var packet = new NotifyInviteGiftPlayerInfoMessage
            {
                charInfoVec = charInfoVec
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            var length1 = reader.ReadUInt16();
            charInfoVec = new InviteGiftPlayerInfo[length1];
            for (var i1 = 0; i1 < length1; i1++)
            {
                charInfoVec[i1] = new InviteGiftPlayerInfo();
                charInfoVec[i1].ReadFromStream(reader);
            }
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            ushort count1 = (ushort)(charInfoVec == null ? 0 : charInfoVec.Length);
            writer.Write(count1);
            for(var i1 = 0; i1 < count1; i1++)
            {
                charInfoVec[i1].WriteToStream(writer);
            }
        }
    }
}
