// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.FriendMessage
{
    public sealed class RELATION_TYPE
    {
        public const int RELATION_TYPE_NONE = 0;
        public const int RELATION_TYPE_FRIEND = 1<<0;// 好友
        public const int RELATION_TYPE_BLACK = 1<<1;// 黑名单
        public const int RELATION_TYPE_FACEBOOK = 1<<3;// Facebook好友
    }
}
