// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.FriendMessage
{
    public sealed class RELATION_COUNT_LIMIT
    {
        public const int RELATION_FRIEND_MAX = 100;// 好友最大人数
        public const int RELATION_BLACK_MAX = 100;// 黑名单最大人数
    }
}
