// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.FriendMessage
{
    /// 请求领取邀请好礼奖励
    public sealed class RequestDrawInviteGiftAwardMessage : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_DRAW_INVITE_GIFT_AWARD;
        public short GetMsgType { get { return MsgType; } }
        public const int DT_DAY = 1;//每日
        public const int DT_TOTAL = 2;//累计
        public string strUuid;// 目标的uuid
        public uint drawType;// 领取类型
        
        public static void Send(string strUuid, uint drawType, object className)
        {
            var packet = new RequestDrawInviteGiftAwardMessage
            {
                strUuid = strUuid,
                drawType = drawType
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            strUuid = reader.ReadString();
            drawType = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(strUuid);
            writer.Write(drawType);
        }
    }
}
