// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.SkillMessage
{
    /// MSGTYPE_DECLARE(MSG_TANK_SKILL_UPGRADE_FAIL)		//服务器
    public sealed class TankSkillUpgradeFail : IProtocol
    {
        public const short MsgType = MessageType.MSG_TANK_SKILL_UPGRADE_FAIL;
        public short GetMsgType { get { return MsgType; } }
        public int error_id;// 参见SKILLUPGRADE_ERRORCODE
        
        public static void Send(int error_id, object className)
        {
            var packet = new TankSkillUpgradeFail
            {
                error_id = error_id
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            error_id = reader.ReadInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(error_id);
        }
    }
}
