// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.TeamMessage
{
    // 通知修改战队名称
    public sealed class NotifyChangeTeamName : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_CHANGE_TEAM_NAME;
        public short GetMsgType { get { return MsgType; } }
        public string info;// 新的战队名称
        
        public static void Send(string info, object className)
        {
            var packet = new NotifyChangeTeamName
            {
                info = info
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            info = reader.ReadString();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(info);
        }
    }
}
