// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

using GameProtocol.ShareTypes;
namespace GameProtocol.TeamMessage
{
    // MSG_NOTIFY_TEAM_JOIN_APPLY
    // 通知有人申请加入战队
    public sealed class NotifyJoinApply : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_TEAM_JOIN_APPLY;
        public short GetMsgType { get { return MsgType; } }
        public BUDDY_BRIEF data;// 申请者信息
        
        public static void Send(BUDDY_BRIEF data, object className)
        {
            var packet = new NotifyJoinApply
            {
                data = data
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            data = new BUDDY_BRIEF();
            data.ReadFromStream(reader);
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            data.WriteToStream(writer);
        }
    }
}
