// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.TeamMessage
{
    // MSGTYPE_DECLARE(MSG_NOTIFY_GUILD_INVITE),
    // 通知军团邀请
    public sealed class NotifyGuildInvite : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_GUILD_INVITE;
        public short GetMsgType { get { return MsgType; } }
        public string szStarter;// 发起者
        public uint GuildId;// 军团id
        public string GuildName;// 军团名称
        public uint TeamId;// 战队id
        public string TeamName;// 战队名
        public byte isJoinGuild;// 加入军团或者加入申请列表
        
        public static void Send(string szStarter, uint guildId, string guildName, uint teamId, string teamName, byte isJoinGuild, object className)
        {
            var packet = new NotifyGuildInvite
            {
                szStarter = szStarter,
                GuildId = guildId,
                GuildName = guildName,
                TeamId = teamId,
                TeamName = teamName,
                isJoinGuild = isJoinGuild
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            szStarter = reader.ReadString();
            GuildId = reader.ReadUInt32();
            GuildName = reader.ReadString();
            TeamId = reader.ReadUInt32();
            TeamName = reader.ReadString();
            isJoinGuild = reader.ReadByte();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(szStarter);
            writer.Write(GuildId);
            writer.Write(GuildName);
            writer.Write(TeamId);
            writer.Write(TeamName);
            writer.Write(isJoinGuild);
        }
    }
}
