// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.TeamMessage
{
    // MSGTYPE_DECLARE(MSG_REQUEST_GUILD_OP),
    // 请求军团操作
    public sealed class RequestGuildOp : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_GUILD_OP;
        public short GetMsgType { get { return MsgType; } }
        public const int GUILD_OP_SETTING_BIT = 1;// 军团设置统一按位标志字段（GUILD_SETTING_BIT）
        public const int GUILD_OP_LEVEL_LIMIT = 2;// 军团设置最低准入等级
        public const int GUILD_OP_LADDER_LIMIT = 3;// 军团设置最低准入段位
        public int type;
        public int iparam;// 参数值
        
        public static void Send(int type, int iparam, object className)
        {
            var packet = new RequestGuildOp
            {
                type = type,
                iparam = iparam
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            type = reader.ReadInt32();
            iparam = reader.ReadInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(type);
            writer.Write(iparam);
        }
    }
}
