// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.TeamMessage
{
    // MSGTYPE_DECLARE(MSG_REQUEST_SET_CHANNEL),
    // 请求设置YY频道号
    public sealed class RequestSetChannel : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_SET_CHANNEL;
        public short GetMsgType { get { return MsgType; } }
        public string szChannel;// yy频道号
        
        public static void Send(string szChannel, object className)
        {
            var packet = new RequestSetChannel
            {
                szChannel = szChannel
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            szChannel = reader.ReadString();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(szChannel);
        }
    }
}
