// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.TeamMessage
{
    public sealed class TEAM_EXT_FLAG_BIT
    {
        public const int TMEF_OPEN_PVE = 1<<0;// 是否开启战队副本
        public const int TMEF_WILL_CLOSE_PVE = 1<<1;// 是否在结算后关闭战队副本
    }
}
