// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.TeamMessage
{
    // 战队信息
    public sealed class TeamInfo
    {
        public uint nTeamId;// 战队id
        public uint nGuildId;// 军团id
        public string strName;// 战队名称
        public string leaderUuid;// 战队队长uuid
        public uint nPlace;// 名次
        public uint nHonorId;// 战队荣誉
        public uint nCreateTime;// 创建时间
        public uint nLevel;// 等级
        public int iCoin;// 资金
        public int iGlory;// 威望
        public int iMerit;// 贡献度，捐给军团资金
        public uint nExtFlag;// TEAM_EXT_FLAG_BIT
        public int iOverdueCount;// 没有支付维护费的次数
        public void ReadFromStream(BinaryReader reader)
        {
            nTeamId = reader.ReadUInt32();
            nGuildId = reader.ReadUInt32();
            strName = reader.ReadString();
            leaderUuid = reader.ReadString();
            nPlace = reader.ReadUInt32();
            nHonorId = reader.ReadUInt32();
            nCreateTime = reader.ReadUInt32();
            nLevel = reader.ReadUInt32();
            iCoin = reader.ReadInt32();
            iGlory = reader.ReadInt32();
            iMerit = reader.ReadInt32();
            nExtFlag = reader.ReadUInt32();
            iOverdueCount = reader.ReadInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(nTeamId);
            writer.Write(nGuildId);
            writer.Write(strName);
            writer.Write(leaderUuid);
            writer.Write(nPlace);
            writer.Write(nHonorId);
            writer.Write(nCreateTime);
            writer.Write(nLevel);
            writer.Write(iCoin);
            writer.Write(iGlory);
            writer.Write(iMerit);
            writer.Write(nExtFlag);
            writer.Write(iOverdueCount);
        }
    }
}
