// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class ACHIEVEMENT_STATE_TYPE
    {
        public const int AST_NONE = 0;
        public const int AST_CLOSED = 1;// 未开启
        public const int AST_OPEN = 2;// 已开启
    }
}
