// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class ACHIEVEMENT_OBJECT
    {
        public const int ACEM_OBJECT_INDIVIDUAL = 1;// 个人
        public const int ACEM_OBJECT_GROUP = 2;// 团体
    }
}
