// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class AI_NPC_ABILITY_TYPE
    {
        public const int AINPC_ABT_EASY = 0;// 炮灰级
        public const int AINPC_ABT_NORMAL = 1;// 普通级
        public const int AINPC_ABT_ELITE = 2;// 精英级
        public const int AINPC_ABT_NORMAL_BOSS = 3;// 普通BOSS
        public const int AINPC_ABT_RARE_BOSS = 4;// 稀有BOSS
        public const int AINPC_ABT_MAX = 5;//
    }
}
