// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class BATTLE_MODE
    {
        public const int MODE_RANDOM = 0;// 随机模式
        public const int MODE_BASE = 1;// 基地模式
        public const int MODE_OCCUPY = 2;// 夺旗模式
        public const int MODE_LIVE = 3;// 生存模式
        public const int MODE_DEAD = 4;// 死亡模式
        public const int MODE_HALLOWMAS = 5;// 万圣节模式
        public const int MODE_EAT_BEANS = 6;// 吃豆模式
        public const int MODE_FIRE_BALL = 7;// 火球赛模式(火球赛专用模式)
        public const int MODE_5_PVE = 8;// 组队副本
        public const int MODE_NEW_BASE = 9;// 新基地模式
        public const int MODE_MAX = 10;
    }
}
