// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class BATTLE_SETTLE_TYPE
    {
        public const int BATTLE_ST_BASE = 0;// 基础
        public const int BATTLE_ST_ACT = 1;// 活动加成
        public const int BATTLE_ST_VIP = 2;// vip加成
        public const int BATTLE_ST_DOUBLE = 3;// 双倍加成
        public const int BATTLE_ST_DAILY = 4;// 每日额外奖励
        public const int BATTLE_ST_AVATAR = 5;// AVATAR额外加成
        public const int BATTLE_ST_DECORATE = 6;// 主题边框（装饰）加成
        public const int BATTLE_ST_MAX = 7;// 枚举最大值（以上枚举需要顺序定义）// 坦克经验的特殊类型
        public const int BATTLE_ST_TANK_EXP_CARD = 20;// 坦克经验卡加成
        public const int BATTLE_ST_HAPPY_RANK_BONUS = 21;// 欢乐赛排名的经验加成
    }
}
