// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class BUFF_EFFECT_MODEL
    {
        public const int BEM_ALL = 0;// 全反应
        public const int BEM_ONLY_SELF = 1;// 仅和自己buff反应
    }
}
