// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class CASH_RECORD_DAY_TYPE
    {
        public const int CRDT_YESTERDAY = 0;//昨天
        public const int CRDT_TODAY = 1;//今天
        public const int CRDT_MAX = 2;
    }
}
