// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class CHAR_STAT_TYPE
    {
        public const int CST_UNKNOWN = 0;
        public const int CST_CHANGE_TEAM = 1;// 更换战队
        public const int CST_BATTLE = 2;// 战斗时间统计
        public const int CST_LOAD = 4;// 客户端加载时间
        public const int CST_FRD_COUNT = 5;// 客户端掉帧次数
        public const int CST_FRD_TIMES = 6;// 客户端掉帧持续时长
        public const int CST_MAP_LOAD = 7;// 地图加载时间
        public const int CST_SEL_MODE = 8;// 用户主动选择玩法的次数统计
        public const int CST_CHARM = 9;// 角色魅力
        public const int CST_MERCY = 10;// 角色浪漫
        public const int CST_RANK_START = 11;// 排行数据起始
        public const int CST_ACT_CHARM = 11;// 角色活动魅力值（倾城值）
        public const int CST_ACT_MERCY = 12;// 角色活动浪漫值（情缘值）
        public const int CST_RLTE_COUNT = 13;// 神秘球使用数量
        public const int CST_SLOT_MACHINE = 14;// 活动转盘计数(老虎机)
        public const int CST_SEND_REDPKT = 15;// 红包活动积分
        public const int CST_RLTE_LUCK = 16;// 幸运活动转盘计数
        public const int CST_RAND_STEP = 17;// 冒险夺宝
        public const int CST_RANK_END = 40;// 排行数据截止
    }
}
