// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class CHECK_TYPE_KIND
    {
        public const int CKTK_NONE = 0;
        public const int CKTK_ADD = 1;// 增加型
        public const int CKTK_ONCE = 2;// 一次性型
        public const int CKTK_REPLACE = 3;// 替换型
        public const int CKTK_EQUAL = 5;// 检查点数量完成相等的
        public const int CKTK_REPLACE_ONCE_LARGER = 6;// 大于当前值时，替换型
    }
}
