// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class ELO_UPDATE_TYPE
    {
        public const int ELO_UP_BATTLE = 0;// 参与匹配战斗变化
        public const int ELO_UP_SESSION = 1;// 赛季刷新
    }
}
