// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class FEATURE_LIMIT_BIT
    {
        public const int FLB_NO_MOVE = 1<<0;//无法被移动
        public const int FLB_NO_JUMP = 1<<1;//无法作为跳跃对象
        public const int FLB_NO_THROW = 1<<2;//无法被投掷
    }
}
