// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class GUILD_SKILL_SLOT
    {
        public const int GSS_NONE = 0;
        public const int GSS_ACTIVE = 1;//主动技能格
        public const int GSS_PASSIVE1 = 5;//被动技能格1
        public const int GSS_PASSIVE2 = 6;//被动技能格2
        public const int GSS_PASSIVE3 = 7;//被动技能格3
        public const int GSS_PASSIVE4 = 8;//被动技能格4
        public const int GSS_MAX = 9;
    }
}
