// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class HARM_TYPE
    {
        public const int HARM_T_PHYSICS = 1;// 物理伤害
        public const int HARM_T_ENERGY = 2;// 能量伤害
        public const int HARM_T_BUILD = 3;// 建筑伤害
        public const int HARM_T_FASTNESS = 4;// 固定伤害
    }
}
