// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class INIT_TANK_ID_TYPE
    {
        public const int GANGTIE_TANK_ID = 10000001;// 钢铁
        public const int ABAO_TANK_ID = 10000003;// 阿宝
        public const int GUMDAM_TANK_ID = 10000019;// 高达
        public const int TIANMA_TANK_ID = 10000035;// 天马
    }
}
