// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class OBJECT_ATTR_TYPE
    {
        public const int ATTR_NONE = 0;
        public const int ATTR_SPEED = 1;// 速度
        public const int ATTR_STAR = 2;// 坦克星级
        public const int ATTR_MAXHP = 3;// 坦克最大血量
        public const int ATTR_FIRE = 4;// 射速
        public const int ATTR_LIFE = 5;// 剩余命数值
        public const int ATTR_HARDNESS = 6;// 装备等级
        public const int ATTR_HP = 7;// 血量
    }
}
