// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class PROPS_FLAG_BIT
    {
        public const int PFB_NO_CUTDOWN = 1<<0;// 不进行范围衰减
        public const int PFB_SHARE_EQUALLY = 1<<1;// 均摊伤害
        public const int PFB_RECURSION_EFFECT = 1<<2;// 存在递归变化效果
        public const int PFB_SEQUENCE_HIT_EFFECT = 1<<3;// 连续命中变化效果
        public const int PFB_NO_FURY = 1<<4;// 不进行暴击
    }
}
