// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class PVE_RECORD_VALID_TYPE
    {
        public const int RECORD_VALID_TIME = 7;// 副本记录存在时间（天）
    }
}
