// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class SETTLE_TYPE
    {
        public const int ST_NONE = 0;// 无
        public const int ST_BATTLE_AWARD = 1;// 战斗奖励
        public const int ST_SOLO_ADD = 2;// 单人收菜奖励
        public const int ST_USE_ITEM = 3;// 使用物品获得
        public const int ST_QUEST_AWARD = 4;// 任务奖励
        public const int ST_DRAW_AWARD = 5;// 活动领奖
        public const int ST_STAGE_AWARD = 6;// 阶段奖励
        public const int ST_PVP_AWARD = 7;// pvp奖励
        public const int ST_CONVERT = 8;// 物品兑换
        public const int ST_ROULETTE = 9;// 轮盘赌
        public const int ST_LEAGUE = 10;// 联赛
        public const int ST_SPLIT_ITEM = 11;// 拆解物品
        public const int ST_PVE_EVAL = 12;// 副本过关评价
        public const int ST_TEAM_PVP_AWARD = 13;// 战队排位赛奖励
        public const int ST_TEAM_PVE_AWARD = 14;// 战队副本奖励
        public const int ST_HAPPLY_AWARD = 15;// 欢乐赛奖励
        public const int ST_BOOSTER_COMPETE_AWARD = 16;// 挑战赛奖励
        public const int ST_SOCIAL_QUEST_AWARD = 17;// 社交任务奖励
        public const int ST_HIRE_TANK = 18;// 租用坦克奖励
        public const int ST_ROULETTE_SLOT_MACHINE = 19;// 老虎机
        public const int ST_ONLINE_PEAK = 20;// 峰值在线活动
        public const int ST_ANNIVERSARY = 21;// 周年庆获得
        public const int ST_CHAR_GIFT = 22;// 角色礼包获得
        public const int ST_DRAGON_BOAT = 23;// 端午活动转盘获得
        public const int ST_SHOP = 24;// 商城购买
        public const int ST_MAIL = 25;// 邮件提取
        public const int ST_RAND_STEP = 26;// 冒险夺宝
        public const int ST_TANK_MAKE = 27;// 坦克制造
        public const int ST_LIMIT_AWARD = 28;// 限制奖励
        public const int ST_TREASURE = 29;// 一元夺宝
        public const int ST_MAX = 30;//
    }
}
