// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class SKILL_PROPERTY
    {
        public const int SKILL_PRO_NONE = 0;// 无
        public const int SKILL_PRO_COMMON = 1;// 普攻
        public const int SKILL_PRO_HURT = 2;// 伤害型技能
        public const int SKILL_PRO_ASSIST = 3;// 辅助型技能
    }
}
