// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class SKILL_MULTI_TYPE
    {
        public const int SKILL_MT_NONE = 0;// 无
        public const int SKILL_MT_CONTINUE = 1;// 子弹连发，技能多次释放
        public const int SKILL_MT_SCATTER = 2;// 散射
        public const int SKILL_MT_CHAIN = 3;// 链式
        public const int SKILL_MT_CT_NOTIFY_ONCE = 4;// 技能多次释放，只在第一次释放时通知客户端播放蓄力动画
        public const int SKILL_MT_SVR_NOTIFY_STOP = 5;// 只在第一次释放时通知客户端，技能释放停止时，服务端会发送停止技能的协议
        public const int SKILL_MT_CYCLE_BULLET = 6;// 来回的子弹
        public const int SKILL_MT_ROUND_OFFSET = 7;// 回旋偏移子弹
    }
}
