// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class SKILL_EFFECT_AMEND_TYPE
    {
        public const int SEAT_NONE = 0;//
        public const int SEAT_AROUND_ENEMYTANK_ADD = 1;// 根据周围的敌方坦克数累加效果值
    }
}
