// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class SKIN_ATTR_TYPE
    {
        public const int SAT_NONE = 0;// 无
        public const int SAT_FIX_ATTR = 1;// 属性 enum ATTR_TYPE
        public const int SAT_BORN_BUFF = 2;// 出生给予Buff
        public const int SAT_TRIG_ATTR = 3;// 被动触发属性
        public const int SAT_MAX = 4;// 最大值
    }
}
