// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class SOCIAL_REL_SUBTYPE
    {
        public const int SRS_MASTER = 0;// 师傅
        public const int SRS_PRENTICE = 1;// 徒弟
        public const int SRS_MAX = 2;
    }
}
