// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class SOCIAL_SUBJECT
    {
        public const int SST_SOURCE = 0;// 发起者，甲方
        public const int SST_TARGET = 1;// 接收者，乙方
        public const int SST_BOTH = 2;// 双方
        public const int SST_ANY = 3;// 双方任一
        public const int SST_NONE = 10;
    }
}
