// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class SOCIAL_CONDTYPE
    {
        public const int SCT_REL_CONFIRMED = 1;// 关系成功确立
        public const int SCT_LEVEL_UPGRADE = 2;// 等级提升
        public const int SCT_INSTANCE_CLEARD = 3;// 地图通关
        public const int SCT_PVP_PAIR = 4;// 参与PVP
        public const int SCT_FIZZ = 5;// 活跃度达到
        public const int SCT_PRESENT = 6;// 赠礼
    }
}
