// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class STORE_TYPE
    {
        public const int STORE_NONE = 0;// 无
        public const int STORE_MYSTERIOUS = 1;// 神秘商店
        public const int STORE_MAX = 2;//
    }
}
