// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class TANK_STTEN_TYPE
    {
        public const int TANK_ST_ATTACK = 1;// 攻击力
        public const int TANK_ST_HP = 2;// 血量
        public const int TANK_ST_CENTESIS = 3;// 穿甲
        public const int TANK_ST_ARMOR = 4;// 护甲
        public const int TANK_ST_EG_ATTACK = 5;// 能量攻击
    }
}
