// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class TEAM_MATCH_STATE
    {
        public const int TMST_NONE = 0;// 无
        public const int TMST_IDLE = 1;// 空闲
        public const int TMST_GOING = 2;// 对战中
        public const int TMST_ARMISTICE = 3;// 休战中
    }
}
