// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class TEAM_POST_TYPE
    {
        public const int TEAM_PT_NONE = 0;// 无
        public const int TEAM_PT_CAPTAIN = 5;// 战队队长
        public const int TEAM_PT_VICE_LEADER = 9;// 副团长
        public const int TEAM_PT_LEADER = 10;// 团长
    }
}
