// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.BulkDataEnum
{
    public sealed class TURNUP_TYPE
    {
        public const int TT_BATTLE_COMMON = 1;// 普通战斗翻牌
        public const int TT_TYRO_PVE = 2;// 新手副本翻牌
        public const int TT_BATTLE_MATCH = 3;// 个人竞技的翻牌
        public const int TT_TEAM_MATCH = 4;// 战队赛的翻牌
        public const int TT_BATTLE_PVE = 5;// 副本的翻牌
    }
}
