// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.BoosterCompeteMessage
{
    /**
     * 通知助手竞技赛战斗历史信息
     * MSGTYPE_DECLARE(MSG_NOTIFY_BOOSTER_BATTLE_HISTORY)
     */
    public sealed class NotifyBstBattleHistory : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_BOOSTER_BATTLE_HISTORY;
        public short GetMsgType { get { return MsgType; } }
        public BOOSTER_BATTLE_INFO[] vecBattleInfo;/// 对战信息列表
        
        public static void Send(BOOSTER_BATTLE_INFO[] vecBattleInfo, object className)
        {
            var packet = new NotifyBstBattleHistory
            {
                vecBattleInfo = vecBattleInfo
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            var length1 = reader.ReadUInt16();
            vecBattleInfo = new BOOSTER_BATTLE_INFO[length1];
            for (var i1 = 0; i1 < length1; i1++)
            {
                vecBattleInfo[i1] = new BOOSTER_BATTLE_INFO();
                vecBattleInfo[i1].ReadFromStream(reader);
            }
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            ushort count1 = (ushort)(vecBattleInfo == null ? 0 : vecBattleInfo.Length);
            writer.Write(count1);
            for(var i1 = 0; i1 < count1; i1++)
            {
                vecBattleInfo[i1].WriteToStream(writer);
            }
        }
    }
}
