// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.ItemMessage
{
    //保存晶片方案结果
    public sealed class NotifySaveCrystalSchemeInfoResultMessage : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_SAVE_CRYSTAL_SCHEME_INFO_RESULT;
        public short GetMsgType { get { return MsgType; } }
        public const int SR_SUCCESS = 0;//成功
        public const int SR_FAIL = 1;//失败
        public uint result;/// 保存结果
        
        public static void Send(uint result, object className)
        {
            var packet = new NotifySaveCrystalSchemeInfoResultMessage
            {
                result = result
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            result = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(result);
        }
    }
}
