// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.ItemMessage
{
    /// 请求道具开启轮盘赌
    public sealed class RequestItemRouletteMessage : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_ITEM_ROULETTE;
        public short GetMsgType { get { return MsgType; } }
        public string itemUuid;// 请求的转盘道具物品UUID
        public byte Batch;// 是否十连抽
        
        public static void Send(string itemUuid, byte batch, object className)
        {
            var packet = new RequestItemRouletteMessage
            {
                itemUuid = itemUuid,
                Batch = batch
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            itemUuid = reader.ReadString();
            Batch = reader.ReadByte();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(itemUuid);
            writer.Write(Batch);
        }
    }
}
