// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.ItemMessage
{
    /// 请求删除物品
    public sealed class RequestSaleItem : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_SALE_ITEM;
        public short GetMsgType { get { return MsgType; } }
        public uint contType;// enum CONTAINER_TYPE
        public short slotNo;// 该物品所在的格子
        
        public static void Send(uint contType, short slotNo, object className)
        {
            var packet = new RequestSaleItem
            {
                contType = contType,
                slotNo = slotNo
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            contType = reader.ReadUInt32();
            slotNo = reader.ReadInt16();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(contType);
            writer.Write(slotNo);
        }
    }
}
