// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

using GameProtocol.BulkDataType;
namespace GameProtocol.ItemMessage
{
    /// 同步轮盘获奖信息给tracksvr
    public sealed class SyncRouletteAward : IProtocol
    {
        public const short MsgType = MessageType.MSG_SYNC_ROULETTE_AWARD;
        public short GetMsgType { get { return MsgType; } }
        public uint Type;// ROULETTE_TYPE
        public OneSvrAward info;
        
        public static void Send(uint type, OneSvrAward info, object className)
        {
            var packet = new SyncRouletteAward
            {
                Type = type,
                info = info
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            Type = reader.ReadUInt32();
            info = new OneSvrAward();
            info.ReadFromStream(reader);
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(Type);
            info.WriteToStream(writer);
        }
    }
}
