// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.TankMakeMessage
{
    public sealed class TREASURE_TYPE
    {
        public const int TT_ONE_ONE = 0;//一元一次夺宝
        public const int TT_FIVE_ONE = 1;//五元一次夺宝
        public const int TT_FIVE_TEN = 2;//五元十次夺宝
    }
}
