// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.LoginProtocol
{
    public sealed class REGION_INFO
    {
        public uint region_id;//区服编号
        public string region_name;//区服名称
        public string gate_realm;//网关域名
        public ushort gate_port;//网关端口
        public string comrealm;//聊天域名
        public ushort comport;//聊天端口
        public char cur_load;//负载情况
        public char is_pvp;//允许PK
        public uint open_time;//开服时间
        public void ReadFromStream(BinaryReader reader)
        {
            region_id = reader.ReadUInt32();
            region_name = reader.ReadString();
            gate_realm = reader.ReadString();
            gate_port = reader.ReadUInt16();
            comrealm = reader.ReadString();
            comport = reader.ReadUInt16();
            cur_load = reader.ReadChar();
            is_pvp = reader.ReadChar();
            open_time = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(region_id);
            writer.Write(region_name);
            writer.Write(gate_realm);
            writer.Write(gate_port);
            writer.Write(comrealm);
            writer.Write(comport);
            writer.Write(cur_load);
            writer.Write(is_pvp);
            writer.Write(open_time);
        }
    }
}
