// Generated by template.py. DO NOT EDIT!
using System;
using System.Collections.Generic;
using System.Xml;

public sealed class TemplateList
{
	public List<string> XMLList = new List<string>() {
		"MapTemplate.xml",
		"TankTemplate.xml",
		"TankTemplate.xml",
	};

	public List<Action<XmlNode>>  FunctionList = new List<Action<XmlNode>>() {
		MapTemplateData.Init,
		TankTemplateData.Init,
		TankTemplateData.Init,
	};
}
