// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.MasterPrenticeMessage
{
    // MSGTYPE_DECLARE(MSG_NOTIFY_MP_RELATION_CREATED)
    // 通知角色关系建立成功
    public sealed class NotifyMPRelationCreated : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_MP_RELATION_CREATED;
        public short GetMsgType { get { return MsgType; } }
        public MASTER_PRENTICE_BRIEF mpBrief;// 角色信息
        
        public static void Send(MASTER_PRENTICE_BRIEF mpBrief, object className)
        {
            var packet = new NotifyMPRelationCreated
            {
                mpBrief = mpBrief
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            mpBrief = new MASTER_PRENTICE_BRIEF();
            mpBrief.ReadFromStream(reader);
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            mpBrief.WriteToStream(writer);
        }
    }
}
