// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.MasterPrenticeMessage
{
    // MSGTYPE_DECLARE(MSG_NOTIFY_MASTER_PRENTICE_INFO)
    // 通知角色的师徒信息
    public sealed class NotifyMasterPrenticeInfo : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_MASTER_PRENTICE_INFO;
        public short GetMsgType { get { return MsgType; } }
        public MASTER_PRENTICE_BRIEF[] vecMPBrief;// 角色师徒信息
        
        public static void Send(MASTER_PRENTICE_BRIEF[] vecMPBrief, object className)
        {
            var packet = new NotifyMasterPrenticeInfo
            {
                vecMPBrief = vecMPBrief
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            var length1 = reader.ReadUInt16();
            vecMPBrief = new MASTER_PRENTICE_BRIEF[length1];
            for (var i1 = 0; i1 < length1; i1++)
            {
                vecMPBrief[i1] = new MASTER_PRENTICE_BRIEF();
                vecMPBrief[i1].ReadFromStream(reader);
            }
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            ushort count1 = (ushort)(vecMPBrief == null ? 0 : vecMPBrief.Length);
            writer.Write(count1);
            for(var i1 = 0; i1 < count1; i1++)
            {
                vecMPBrief[i1].WriteToStream(writer);
            }
        }
    }
}
