// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.BuffMessage
{
    /// Server -> Client 取消BUFF
    /// MSGTYPE_DECLARE(MSG_NOTIFY_REMOVE_BUFF),
    // 通知对象失去buff
    public sealed class NotifyRemoveBuff : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_REMOVE_BUFF;
        public short GetMsgType { get { return MsgType; } }
        public ulong ObjId;// 对象id
        public ulong BuffInstId;//Buff实例ID
        
        public static void Send(ulong objId, ulong buffInstId, object className)
        {
            var packet = new NotifyRemoveBuff
            {
                ObjId = objId,
                BuffInstId = buffInstId
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            ObjId = reader.ReadUInt64();
            BuffInstId = reader.ReadUInt64();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(ObjId);
            writer.Write(BuffInstId);
        }
    }
}
