// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.EchoMessage
{
    // ----------------------------------------------------------------------
    /// @file           protocol/EchoRequest.h
    /// @brief
    /// @author         Linyixiong
    /// @copyright      Sixcube Information Technology Co,. Ltd. (2012)
    /// @date           2011-5-27 16:27:00
    // -----------------------------------------------------------------------
    /// MSGTYPE_DECLARE(MSG_ECHO_REQUEST)
    public sealed class EchoRequest : IProtocol
    {
        public const short MsgType = MessageType.MSG_ECHO_REQUEST;
        public short GetMsgType { get { return MsgType; } }
        public uint ObjId;// 对象id
        public string szText;
        
        public static void Send(uint objId, string szText, object className)
        {
            var packet = new EchoRequest
            {
                ObjId = objId,
                szText = szText
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            ObjId = reader.ReadUInt32();
            szText = reader.ReadString();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(ObjId);
            writer.Write(szText);
        }
    }
}
