// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.RoomMessage
{
    public sealed class ENTER_SCENE_TYPE
    {
        public const int EST_NATURAL = 0;// 正常进入
        public const int EST_MIDWAY = 1;// 中途加入
        public const int EST_LOOKER = 2;// 观战
    }
}
