// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.RoomMessage
{
    // 通知组队副本地图ID
    public sealed class NotifyTeamPveMapId : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_TEAM_PVE_MAP_ID;
        public short GetMsgType { get { return MsgType; } }
        public uint nMapId;// 地图Id
        
        public static void Send(uint nMapId, object className)
        {
            var packet = new NotifyTeamPveMapId
            {
                nMapId = nMapId
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            nMapId = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(nMapId);
        }
    }
}
