// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.RoomMessage
{
    public sealed class OTHER_GUILD_ROOM_DATA
    {
        public uint RoomId;// 房间ID
        public string strRoomLeaderName;// 房主名称
        public uint AvatarId;// 房主avatar
        public uint RoomBoosterAttack;// 房间助手战力
        public uint Num;// 当前人数
        public uint MaxNum;// 最大人数
        public void ReadFromStream(BinaryReader reader)
        {
            RoomId = reader.ReadUInt32();
            strRoomLeaderName = reader.ReadString();
            AvatarId = reader.ReadUInt32();
            RoomBoosterAttack = reader.ReadUInt32();
            Num = reader.ReadUInt32();
            MaxNum = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(RoomId);
            writer.Write(strRoomLeaderName);
            writer.Write(AvatarId);
            writer.Write(RoomBoosterAttack);
            writer.Write(Num);
            writer.Write(MaxNum);
        }
    }
}
