// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.RoomMessage
{
    // MSGTYPE_DECLARE(MSG_REQUEST_PLAYER_LIST),
    // 客户端请求玩家列表
    public sealed class RequestPlayerList : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_PLAYER_LIST;
        public short GetMsgType { get { return MsgType; } }
        public byte listType;// enum PLAYER_LIST_TYPE,玩家列表类型前4个
        public int Site;// 请求页的起始位置
        
        public static void Send(byte listType, int site, object className)
        {
            var packet = new RequestPlayerList
            {
                listType = listType,
                Site = site
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            listType = reader.ReadByte();
            Site = reader.ReadInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(listType);
            writer.Write(Site);
        }
    }
}
