// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.RoomMessage
{
    /// 请求退出战斗结算
    public sealed class RequestExitBattleEnd : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_EXIT_BATTLEEND;
        public short GetMsgType { get { return MsgType; } }
        public byte type;// enum BATTLEEND_EXIT_TYPE
        
        public static void Send(byte type, object className)
        {
            var packet = new RequestExitBattleEnd
            {
                type = type
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            type = reader.ReadByte();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(type);
        }
    }
}
