// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.RoomMessage
{
    // 房间状态枚举
    // 等待状态
    // 等待配对状态
    // 战斗状态
    // 房间信息
    public sealed class RoomInfo
    {
        public uint RoomId;// 房间id
        public uint Num;// 人数
        public uint Max;// 最大人数
        public uint mapId;// 地图id
        public uint mode;// 房间模式 enum BATTLE_MODE， 匹配模式选择开启，通知client
        public byte state;// 房间状态 enum ROOM_STATE_TYPE
        public byte isValidate;// 是否有密码
        public byte type;// 房间类型
        public string szName;// 房间名
        public uint TeamId;// 战队赛的战队id
        public void ReadFromStream(BinaryReader reader)
        {
            RoomId = reader.ReadUInt32();
            Num = reader.ReadUInt32();
            Max = reader.ReadUInt32();
            mapId = reader.ReadUInt32();
            mode = reader.ReadUInt32();
            state = reader.ReadByte();
            isValidate = reader.ReadByte();
            type = reader.ReadByte();
            szName = reader.ReadString();
            TeamId = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(RoomId);
            writer.Write(Num);
            writer.Write(Max);
            writer.Write(mapId);
            writer.Write(mode);
            writer.Write(state);
            writer.Write(isValidate);
            writer.Write(type);
            writer.Write(szName);
            writer.Write(TeamId);
        }
    }
}
