// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.RoomMessage
{
    // MSGTYPE_DECLARE(MSG_SYNC_LOAD_DELAY),
    // 同步客户端加载进度和网络延迟
    public sealed class SyncLoadAndDelay : IProtocol
    {
        public const short MsgType = MessageType.MSG_SYNC_LOAD_DELAY;
        public short GetMsgType { get { return MsgType; } }
        public uint SceneId;// 玩家当前战场id
        public uint TankId;// 角色id
        public uint Delay;// 客户端延迟
        public uint Loaded;// 客户端加载进度
        
        public static void Send(uint sceneId, uint tankId, uint delay, uint loaded, object className)
        {
            var packet = new SyncLoadAndDelay
            {
                SceneId = sceneId,
                TankId = tankId,
                Delay = delay,
                Loaded = loaded
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            SceneId = reader.ReadUInt32();
            TankId = reader.ReadUInt32();
            Delay = reader.ReadUInt32();
            Loaded = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(SceneId);
            writer.Write(TankId);
            writer.Write(Delay);
            writer.Write(Loaded);
        }
    }
}
