// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.SocialMessge
{
    // 请求领取一个临时师徒关系的邀请码
    public sealed class ConfirmSocialTicket : IProtocol
    {
        public const short MsgType = MessageType.MSG_CONFIRM_SOCIAL_TICKET;
        public short GetMsgType { get { return MsgType; } }
        public string ticket;// 临时师徒关系的邀请码
        
        public static void Send(string ticket, object className)
        {
            var packet = new ConfirmSocialTicket
            {
                ticket = ticket
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            ticket = reader.ReadString();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(ticket);
        }
    }
}
