// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

using GameProtocol.BulkDataType;
namespace GameProtocol.NpcMessage
{
    // MSGTYPE_DECLARE(MSG_NPC_CREATE_OBJECT),
    // npc->gamesvr 通知创建npc/ainpc
    public sealed class NpcCreateObject : IProtocol
    {
        public const short MsgType = MessageType.MSG_NPC_CREATE_OBJECT;
        public short GetMsgType { get { return MsgType; } }
        public uint SceneId;// 战场id
        public AiNpcInfo aiNpcInfo;// npc数据
        
        public static void Send(uint sceneId, AiNpcInfo aiNpcInfo, object className)
        {
            var packet = new NpcCreateObject
            {
                SceneId = sceneId,
                aiNpcInfo = aiNpcInfo
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            SceneId = reader.ReadUInt32();
            aiNpcInfo = new AiNpcInfo();
            aiNpcInfo.ReadFromStream(reader);
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(SceneId);
            aiNpcInfo.WriteToStream(writer);
        }
    }
}
