// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.NpcMessage
{
    // MSGTYPE_DECLARE(MSG_NPC_SERVER_REG_RESPONE),    // 游戏服务器对NPC服务器注册的回应MSG_NPC_SERVER_REG_RESPONE
    public sealed class NpcServerRegResponse : IProtocol
    {
        public const short MsgType = MessageType.MSG_NPC_SERVER_REG_RESPONE;
        public short GetMsgType { get { return MsgType; } }
        public const int NS_FRESH = 0;
        public const int NS_RECONNECT = 1;
        public const int NS_DUPLICATE = 2;
        public int state;
        
        public static void Send(int state, object className)
        {
            var packet = new NpcServerRegResponse
            {
                state = state
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            state = reader.ReadInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(state);
        }
    }
}
