// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.MailMessage
{
    public sealed class MAIL_SEND_MODE
    {
        public const int MAIL_SEND_CHAR = 0;// 玩家发送的普通邮件
        public const int MAIL_SEND_BACK = 1;// 退回的邮件
        public const int MAIL_SEND_PAY = 2;// 玩家发送的需要付款的邮件
        public const int MAIL_SEND_FOR_PAY = 3;// 支付款项的回复邮件
        public const int MAIL_SEND_SYS = 4;// 系统发送的邮件
        public const int MAIL_SEND_TURNUP_GET = 5;// 翻牌系统给与物品
        public const int MAIL_SEND_LARGESS_GOODS = 6;// 玩家赠送的商城物品
        public const int MAIL_SEND_BUY_GOODS = 7;// 商城购买物品，包裹满后邮寄
        public const int MAIL_SEND_AUTO_DEBUS = 8;// 过期，自动卸下
        public const int MAIL_SEND_STAGE_REWARD = 9;// 玩家阶段性奖励发送的物品
        public const int MAIL_SEND_ROULETTE = 10;// 轮盘赌获得的物品
        public const int MAIL_SEND_LEAGUE_REWARD = 11;// 联赛获得的奖励
        public const int MAIL_SEND_TICKET = 12;// 月票物品使用获得邮件信息（玩家不能删除）
    }
}
