// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.MailMessage
{
    /// 通知操作结果
    public sealed class NotifyMailOperateResult : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_MAIL_OP_RET;
        public short GetMsgType { get { return MsgType; } }
        public int result;
        public int opType;
        public string strMailUuid;// 邮件的uuid
        
        public static void Send(int result, int opType, string strMailUuid, object className)
        {
            var packet = new NotifyMailOperateResult
            {
                result = result,
                opType = opType,
                strMailUuid = strMailUuid
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            result = reader.ReadInt32();
            opType = reader.ReadInt32();
            strMailUuid = reader.ReadString();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(result);
            writer.Write(opType);
            writer.Write(strMailUuid);
        }
    }
}
