// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.SceneMessage
{
    public sealed class BATTLE_WIN_TYPE
    {
        public const int BWT_COMPLETE_WIN = 0;// 完胜 对应 完败
        public const int BWT_WIN = 1;// 胜利 对应 失败
        public const int BWT_SMALL_WIN = 2;// 险胜 对应 惜败
        public const int BWT_ENEMY_SURRENDER = 3;// 敌方投降胜利
        public const int BWT_DOGFALL = 4;// 平局
        public const int BWT_MAX = 5;
    }
}
