// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.SceneMessage
{
    // MSGTYPE_DECLARE(MSC_CREATE_SCENE_PROPS),
    // 通知创建场景道具
    public sealed class CreateSceneProps : IProtocol
    {
        public const short MsgType = MessageType.MSC_CREATE_SCENE_PROPS;
        public short GetMsgType { get { return MsgType; } }
        public uint SceneId;// 战场id
        public uint PropsId;// 道具id
        public int Count;// 道具数量
        
        public static void Send(uint sceneId, uint propsId, int count, object className)
        {
            var packet = new CreateSceneProps
            {
                SceneId = sceneId,
                PropsId = propsId,
                Count = count
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            SceneId = reader.ReadUInt32();
            PropsId = reader.ReadUInt32();
            Count = reader.ReadInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(SceneId);
            writer.Write(PropsId);
            writer.Write(Count);
        }
    }
}
