// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.SceneMessage
{
    // MSGTYPE_DECLARE(MSG_NOTIFY_NO_SELECT_TANK_PUNISH),
    /// 通知未选坦克惩罚
    public sealed class NotifyNoSelectTankPunishMessage : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_NO_SELECT_TANK_PUNISH;
        public short GetMsgType { get { return MsgType; } }
        public uint sceneId;
        public uint roomType;
        
        public static void Send(uint sceneId, uint roomType, object className)
        {
            var packet = new NotifyNoSelectTankPunishMessage
            {
                sceneId = sceneId,
                roomType = roomType
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            sceneId = reader.ReadUInt32();
            roomType = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(sceneId);
            writer.Write(roomType);
        }
    }
}
