// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.SceneMessage
{
    // 通知投降冷却时间
    public sealed class NotifySurrenderVotationCoolTime : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_SURRENDER_VOTATION_COOL_TIME;
        public short GetMsgType { get { return MsgType; } }
        public uint Time;// 允许发起投降表决的时间戳
        
        public static void Send(uint time, object className)
        {
            var packet = new NotifySurrenderVotationCoolTime
            {
                Time = time
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            Time = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(Time);
        }
    }
}
