// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.SceneMessage
{
    // 通知玩家，坦克被锁定
    public sealed class NotifyTankLocked : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_TANK_LOCKED;
        public short GetMsgType { get { return MsgType; } }
        public uint CharOid;// 锁定该坦克的玩家OID
        public uint TankId;// 坦克ID
        public uint TankCont;// 坦克容器类型 enum TANK_CONTAINER_TYPE
        
        public static void Send(uint charOid, uint tankId, uint tankCont, object className)
        {
            var packet = new NotifyTankLocked
            {
                CharOid = charOid,
                TankId = tankId,
                TankCont = tankCont
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            CharOid = reader.ReadUInt32();
            TankId = reader.ReadUInt32();
            TankCont = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(CharOid);
            writer.Write(TankId);
            writer.Write(TankCont);
        }
    }
}
