// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

using GameProtocol.BulkDataType;
namespace GameProtocol.SceneMessage
{
    // MSGTYPE_DECLARE(MSG_NOTIFY_SCENE_OBJECT),
    // 通知战场对象数据
    public sealed class NotifySceneObject : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_SCENE_OBJECT;
        public short GetMsgType { get { return MsgType; } }
        public ObjInfo[] objVec;// 场景对象数据
        
        public static void Send(ObjInfo[] objVec, object className)
        {
            var packet = new NotifySceneObject
            {
                objVec = objVec
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            var length1 = reader.ReadUInt16();
            objVec = new ObjInfo[length1];
            for (var i1 = 0; i1 < length1; i1++)
            {
                objVec[i1] = new ObjInfo();
                objVec[i1].ReadFromStream(reader);
            }
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            ushort count1 = (ushort)(objVec == null ? 0 : objVec.Length);
            writer.Write(count1);
            for(var i1 = 0; i1 < count1; i1++)
            {
                objVec[i1].WriteToStream(writer);
            }
        }
    }
}
