// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.SceneMessage
{
    // 通知战斗即将结算
    public sealed class NotifyEndOnHand : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_END_ONHAND;
        public short GetMsgType { get { return MsgType; } }
        public uint endTime;// 战斗结束的时间戳
        
        public static void Send(uint endTime, object className)
        {
            var packet = new NotifyEndOnHand
            {
                endTime = endTime
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            endTime = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(endTime);
        }
    }
}
