// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.SceneMessage
{
    /*
     * server->client 通知客户端更新能量条
     */
    public sealed class ObjectMp
    {
        public ulong objId;// 对象id
        public int objMp;// 对象MP
        public void ReadFromStream(BinaryReader reader)
        {
            objId = reader.ReadUInt64();
            objMp = reader.ReadInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(objId);
            writer.Write(objMp);
        }
    }
}
