// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.SceneMessage
{
    // Client通知track玩家锁定坦克
    public sealed class RequestLockTank : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_LOCK_TANK;
        public short GetMsgType { get { return MsgType; } }
        public uint SceneId;// 战场ID
        
        public static void Send(uint sceneId, object className)
        {
            var packet = new RequestLockTank
            {
                SceneId = sceneId
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            SceneId = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(SceneId);
        }
    }
}
