// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.SceneMessage
{
    // MSGTYPE_DECLARE(MSG_SYNC_OCCUPY_DATA),
    // 同步争夺点占领信息
    public sealed class SyncOccupyData : IProtocol
    {
        public const short MsgType = MessageType.MSG_SYNC_OCCUPY_DATA;
        public short GetMsgType { get { return MsgType; } }
        public OccupyInfo[] occupyVec;// 争夺点信息
        
        public static void Send(OccupyInfo[] occupyVec, object className)
        {
            var packet = new SyncOccupyData
            {
                occupyVec = occupyVec
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            var length1 = reader.ReadUInt16();
            occupyVec = new OccupyInfo[length1];
            for (var i1 = 0; i1 < length1; i1++)
            {
                occupyVec[i1] = new OccupyInfo();
                occupyVec[i1].ReadFromStream(reader);
            }
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            ushort count1 = (ushort)(occupyVec == null ? 0 : occupyVec.Length);
            writer.Write(count1);
            for(var i1 = 0; i1 < count1; i1++)
            {
                occupyVec[i1].WriteToStream(writer);
            }
        }
    }
}
