// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.SceneMessage
{
    // 同步选坦克阶段分配的坦克
    public sealed class SyncSelectedTank : IProtocol
    {
        public const short MsgType = MessageType.MSG_SYNC_TRACK_SELECTED_TANK;
        public short GetMsgType { get { return MsgType; } }
        public uint TankId;// 坦克ID
        public uint TankCont;// 坦克容器
        public uint TankLevel;// 坦克等级
        
        public static void Send(uint tankId, uint tankCont, uint tankLevel, object className)
        {
            var packet = new SyncSelectedTank
            {
                TankId = tankId,
                TankCont = tankCont,
                TankLevel = tankLevel
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            TankId = reader.ReadUInt32();
            TankCont = reader.ReadUInt32();
            TankLevel = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(TankId);
            writer.Write(TankCont);
            writer.Write(TankLevel);
        }
    }
}
