// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.TradeMessage
{
    /// 通知可以赠送商品给他人(buddy -> gate)
    public sealed class NotifyCanPresentGoods : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_CAN_PRESENT_GOODS;
        public short GetMsgType { get { return MsgType; } }
        public uint goodsId;// 商品id
        public int price;// 赠送单价
        public int count;// 赠送数量
        public string receiverName;// 接收者名字
        public string text;// 赠言
        public string receiverUuid;// 接收者Uuid
        public uint receiverOid;// 接收者Oid
        
        public static void Send(uint goodsId, int price, int count, string receiverName, string text, string receiverUuid, uint receiverOid, object className)
        {
            var packet = new NotifyCanPresentGoods
            {
                goodsId = goodsId,
                price = price,
                count = count,
                receiverName = receiverName,
                text = text,
                receiverUuid = receiverUuid,
                receiverOid = receiverOid
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            goodsId = reader.ReadUInt32();
            price = reader.ReadInt32();
            count = reader.ReadInt32();
            receiverName = reader.ReadString();
            text = reader.ReadString();
            receiverUuid = reader.ReadString();
            receiverOid = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(goodsId);
            writer.Write(price);
            writer.Write(count);
            writer.Write(receiverName);
            writer.Write(text);
            writer.Write(receiverUuid);
            writer.Write(receiverOid);
        }
    }
}
