// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.ChapterMessage
{
    // MSGTYPE_DECLARE(MSG_REQUEST_SOLO_PVE_INFO)
    // 请求副本数据信息
    public sealed class RequestSoloPveInfoMessage : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_SOLO_PVE_INFO;
        public short GetMsgType { get { return MsgType; } }
        
        public static void Send(object className)
        {
            var packet = new RequestSoloPveInfoMessage();
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
        }
    }
}
