// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.ChapterMessage
{
    //MSGTYPE_DECLARE_ASSIGN(MSG_PVE_REQUEST_REFRESH_REWARD),
    //请求刷新PVE副本的结算信息
    public sealed class RequestRefreshReward : IProtocol
    {
        public const short MsgType = MessageType.MSG_PVE_REQUEST_REFRESH_REWARD;
        public short GetMsgType { get { return MsgType; } }
        public uint ChapterId;// 请求刷新的章节的奖励
        
        public static void Send(uint chapterId, object className)
        {
            var packet = new RequestRefreshReward
            {
                ChapterId = chapterId
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            ChapterId = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(ChapterId);
        }
    }
}
