// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.ChapterMessage
{
    // ----------------------------------------------------------------------
    ///    @file            protocol/ChapterMessage.h
    ///    @brief
    ///    @author          libo
    ///    @copyright       Sixcube Information Technology Co,. Ltd. (2012)
    ///    @date
    // ----------------------------------------------------------------------
    // MSGTYPE_DECLARE(MSG_PVE_SELECT_SCENE),
    // 请求选择开始某个章节内的关卡
    public sealed class RequestSelectChapterScene : IProtocol
    {
        public const short MsgType = MessageType.MSG_PVE_SELECT_SCENE;
        public short GetMsgType { get { return MsgType; } }
        public uint MapId;// 关卡编号
        
        public static void Send(uint mapId, object className)
        {
            var packet = new RequestSelectChapterScene
            {
                MapId = mapId
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            MapId = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(MapId);
        }
    }
}
