// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.ChapterMessage
{
    // MSGTYPE_DECLARE(MSG_PVE_REQUEST_TUTOR_MAP)
    // 请求选择开始某个训练副本
    public sealed class RequestSelectTutorMap : IProtocol
    {
        public const short MsgType = MessageType.MSG_PVE_REQUEST_TUTOR_MAP;
        public short GetMsgType { get { return MsgType; } }
        public uint MapId;// 关卡编号
        
        public static void Send(uint mapId, object className)
        {
            var packet = new RequestSelectTutorMap
            {
                MapId = mapId
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            MapId = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(MapId);
        }
    }
}
