// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.ClusterMessage
{
    //MSGTYPE_DECLARE(MSG_CLUSTER_GATE_PLAYERSYNC),
    //网关->游戏服务器，发送初始角色信息
    public sealed class ClusterRequestSyncPlayer : IProtocol
    {
        public const short MsgType = MessageType.MSG_CLUSTER_GATE_PLAYERSYNC;
        public short GetMsgType { get { return MsgType; } }
        public uint account_oid;
        public ushort isLogin;// 是否登录，false为跳地图
        public uint ip;// ip地址
        public string token;// 客户端token
        
        public static void Send(uint account_oid, ushort isLogin, uint ip, string token, object className)
        {
            var packet = new ClusterRequestSyncPlayer
            {
                account_oid = account_oid,
                isLogin = isLogin,
                ip = ip,
                token = token
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            account_oid = reader.ReadUInt32();
            isLogin = reader.ReadUInt16();
            ip = reader.ReadUInt32();
            token = reader.ReadString();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(account_oid);
            writer.Write(isLogin);
            writer.Write(ip);
            writer.Write(token);
        }
    }
}
