// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.ClusterMessage
{
    //MSGTYPE_DECLARE(MSG_CLUSTER_AUTH_SESSIONSTART),
    //网关->认证服务器，有登陆请求激活
    public sealed class ClusterAuthSessionStart : IProtocol
    {
        public const short MsgType = MessageType.MSG_CLUSTER_AUTH_SESSIONSTART;
        public short GetMsgType { get { return MsgType; } }
        public uint session;
        public uint client_cid;
        public uint AcctId;
        
        public static void Send(uint session, uint client_cid, uint acctId, object className)
        {
            var packet = new ClusterAuthSessionStart
            {
                session = session,
                client_cid = client_cid,
                AcctId = acctId
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            session = reader.ReadUInt32();
            client_cid = reader.ReadUInt32();
            AcctId = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(session);
            writer.Write(client_cid);
            writer.Write(AcctId);
        }
    }
}
