// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.ClusterMessage
{
    //MSGTYPE_DECLARE(MSG_CLUSTER_AUTH_NOTIFY_SCLOSE),
    //认证中心->，有SESSION已经放弃
    public sealed class ClusterAuthNotifySessionClose : IProtocol
    {
        public const short MsgType = MessageType.MSG_CLUSTER_AUTH_NOTIFY_SCLOSE;
        public short GetMsgType { get { return MsgType; } }
        public ushort reason;//关闭原因 AUTH_SESSION_RESULT
        public uint region_id;//区服的ID
        public uint svr_uid;//通知事件源所在的服务器UID
        public uint client_cid;//所在服务器的连接号
        public uint session;// SessionKey
        public uint AcctId;// 账号id
        
        public static void Send(ushort reason, uint region_id, uint svr_uid, uint client_cid, uint session, uint acctId, object className)
        {
            var packet = new ClusterAuthNotifySessionClose
            {
                reason = reason,
                region_id = region_id,
                svr_uid = svr_uid,
                client_cid = client_cid,
                session = session,
                AcctId = acctId
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            reason = reader.ReadUInt16();
            region_id = reader.ReadUInt32();
            svr_uid = reader.ReadUInt32();
            client_cid = reader.ReadUInt32();
            session = reader.ReadUInt32();
            AcctId = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(reason);
            writer.Write(region_id);
            writer.Write(svr_uid);
            writer.Write(client_cid);
            writer.Write(session);
            writer.Write(AcctId);
        }
    }
}
