// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.ClusterMessage
{
    // MSGTYPE_DECLARE(MSG_NOTIFY_HOST_URL),
    // 通知服务器的url地址
    public sealed class NotifyHostUrl : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_HOST_URL;
        public short GetMsgType { get { return MsgType; } }
        public string matchUrl;// 联赛服务器url
        
        public static void Send(string matchUrl, object className)
        {
            var packet = new NotifyHostUrl
            {
                matchUrl = matchUrl
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            matchUrl = reader.ReadString();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(matchUrl);
        }
    }
}
