// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.LeagueMessage
{
    /// 通知联赛房间创建结果
    public sealed class GlobalJoinLeagueRoomOK : IProtocol
    {
        public const short MsgType = MessageType.MSG_GLOBAL_NOTIFY_JOIN_LEAGUE_ROOM_OK;
        public short GetMsgType { get { return MsgType; } }
        public uint RoomId;// 房间ID
        
        public static void Send(uint roomId, object className)
        {
            var packet = new GlobalJoinLeagueRoomOK
            {
                RoomId = roomId
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            RoomId = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(RoomId);
        }
    }
}
