// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.LeagueMessage
{
    // MSGTYPE_DECLARE(MSG_GLOBAL_LEAGUE_CHALLENGE_LIST),
    // 联赛返回挑战列表Global->Track
    public sealed class LeagueGlobalChallengeList : IProtocol
    {
        public const short MsgType = MessageType.MSG_GLOBAL_LEAGUE_CHALLENGE_LIST;
        public short GetMsgType { get { return MsgType; } }
        public uint Contest;// 联赛对阵
        public uint Cluster;// 请求的大区
        public uint Team;// 所在的队伍
        public uint AcctOid;// 请求的玩家
        public LeagueChallenge[] challenges;// 挑战列表
        
        public static void Send(uint contest, uint cluster, uint team, uint acctOid, LeagueChallenge[] challenges, object className)
        {
            var packet = new LeagueGlobalChallengeList
            {
                Contest = contest,
                Cluster = cluster,
                Team = team,
                AcctOid = acctOid,
                challenges = challenges
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            Contest = reader.ReadUInt32();
            Cluster = reader.ReadUInt32();
            Team = reader.ReadUInt32();
            AcctOid = reader.ReadUInt32();
            var length5 = reader.ReadUInt16();
            challenges = new LeagueChallenge[length5];
            for (var i5 = 0; i5 < length5; i5++)
            {
                challenges[i5] = new LeagueChallenge();
                challenges[i5].ReadFromStream(reader);
            }
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(Contest);
            writer.Write(Cluster);
            writer.Write(Team);
            writer.Write(AcctOid);
            ushort count5 = (ushort)(challenges == null ? 0 : challenges.Length);
            writer.Write(count5);
            for(var i5 = 0; i5 < count5; i5++)
            {
                challenges[i5].WriteToStream(writer);
            }
        }
    }
}
