// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.LeagueMessage
{
    //MSGTYPE_DECLARE_ASSIGN(MSG_LEAGUE_REQUEST_ENROLL, 190),
    //请求报名到某个赛事
    public sealed class LeagueRequestEnroll : IProtocol
    {
        public const short MsgType = MessageType.MSG_LEAGUE_REQUEST_ENROLL;
        public short GetMsgType { get { return MsgType; } }
        public uint teaid;// 报名的队伍编号
        public uint session;// 要报名的赛事实例
        public uint zone_id;// 要报名到的分区
        
        public static void Send(uint teaid, uint session, uint zone_id, object className)
        {
            var packet = new LeagueRequestEnroll
            {
                teaid = teaid,
                session = session,
                zone_id = zone_id
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            teaid = reader.ReadUInt32();
            session = reader.ReadUInt32();
            zone_id = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(teaid);
            writer.Write(session);
            writer.Write(zone_id);
        }
    }
}
