// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.WorldMessage
{
    public sealed class TRIGGER_OBJ
    {
        public const int TO_NONE = 0;// 不特定监视某种目标
        public const int TO_PLAYER = 1;// 仅仅针对玩家
        public const int TO_NPC = 2;// 仅仅针对NPC
        public const int TO_NPC_PLAYER = 3;// 针对NPC和玩家
    }
}
