// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.WorldMessage
{
    public sealed class TRIGGER_TYPE
    {
        public const int TT_TRIGGER = 0;// 目标监视触发器 enum TRIGGER_OBJ
        public const int TT_PVP = 1;// PVP区域
    }
}
