// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.TankMessage
{
    // 通知买活或者买命信息
    public sealed class NotifyBuyLifeInfo : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_BUY_LIFE_INFO;
        public short GetMsgType { get { return MsgType; } }
        public int FreeCount;// 免费次数
        public int Coin;// 需要的银币 <= 0 表示不能用银币复活
        public int Cash;// 需要的点券 <= 0 表示不能用点券复活
        
        public static void Send(int freeCount, int coin, int cash, object className)
        {
            var packet = new NotifyBuyLifeInfo
            {
                FreeCount = freeCount,
                Coin = coin,
                Cash = cash
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            FreeCount = reader.ReadInt32();
            Coin = reader.ReadInt32();
            Cash = reader.ReadInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(FreeCount);
            writer.Write(Coin);
            writer.Write(Cash);
        }
    }
}
