// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.TankMessage
{
    // 坦克删除坦克
    public sealed class NotifyDeleteTank : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_TANK_DELETE;
        public short GetMsgType { get { return MsgType; } }
        public string tankUuid;
        
        public static void Send(string tankUuid, object className)
        {
            var packet = new NotifyDeleteTank
            {
                tankUuid = tankUuid
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            tankUuid = reader.ReadString();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(tankUuid);
        }
    }
}
