// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.TankMessage
{
    // 通知扣除赠送租用坦克的货币
    public sealed class NotifyConsumeHireTankCoin : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_CONSUME_HIRE_TANK_COIN;
        public short GetMsgType { get { return MsgType; } }
        public uint TankId;// 坦克ID
        public uint TankLevel;// 坦克等级
        public uint HireTime;// 租用时间
        public uint CoinVal;// 租用价格
        public uint TargetOid;// 目标玩家的Oid
        public string strTargetUuid;// 目标玩家的UUID
        
        public static void Send(uint tankId, uint tankLevel, uint hireTime, uint coinVal, uint targetOid, string strTargetUuid, object className)
        {
            var packet = new NotifyConsumeHireTankCoin
            {
                TankId = tankId,
                TankLevel = tankLevel,
                HireTime = hireTime,
                CoinVal = coinVal,
                TargetOid = targetOid,
                strTargetUuid = strTargetUuid
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            TankId = reader.ReadUInt32();
            TankLevel = reader.ReadUInt32();
            HireTime = reader.ReadUInt32();
            CoinVal = reader.ReadUInt32();
            TargetOid = reader.ReadUInt32();
            strTargetUuid = reader.ReadString();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(TankId);
            writer.Write(TankLevel);
            writer.Write(HireTime);
            writer.Write(CoinVal);
            writer.Write(TargetOid);
            writer.Write(strTargetUuid);
        }
    }
}
