// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.TankMessage
{
    public sealed class PROPS_OP_TYPE
    {
        public const int DROP_PROPS = 1;// 丢弃道具
        public const int PICK_PROPS = 100;// 拾取道具，服务端通知客户端
        public const int SYNC_PROPS = 101;// 同步剩余数量
    }
}
