// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.TankMessage
{
    // 请求更换坦克皮肤
    public sealed class RequestChangeSkin : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_TANK_CHANGE_SKIN;
        public short GetMsgType { get { return MsgType; } }
        public string tankUuid;// 坦克的uuid
        public string skinUuid;// 皮肤uuid
        public byte contType;// 坦克容器类型 enum TANK_CONTAINER_TYPE
        
        public static void Send(string tankUuid, string skinUuid, byte contType, object className)
        {
            var packet = new RequestChangeSkin
            {
                tankUuid = tankUuid,
                skinUuid = skinUuid,
                contType = contType
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            tankUuid = reader.ReadString();
            skinUuid = reader.ReadString();
            contType = reader.ReadByte();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(tankUuid);
            writer.Write(skinUuid);
            writer.Write(contType);
        }
    }
}
