// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.TankMessage
{
    // 请求兑换研究进度为经验
    public sealed class RequestRecycleTankResearch : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_RECYCLE_TANK_RESEARCH;
        public short GetMsgType { get { return MsgType; } }
        public uint TankId;/// 坦克ID
        
        public static void Send(uint tankId, object className)
        {
            var packet = new RequestRecycleTankResearch
            {
                TankId = tankId
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            TankId = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(TankId);
        }
    }
}
