// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.TankMessage
{
    // 请求租用坦克
    public sealed class RequestHireTank : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_TANK_HIRE;
        public short GetMsgType { get { return MsgType; } }
        public uint TankId;// 坦克的id
        public int TankLevel;// 租用坦克的等级
        public uint HireTime;// 租用时间 （小时）
        public uint CoinType;// 货币类型 coin_type
        public uint CoinValue;// 价格
        public byte VipFreeHire;// 是否VIP免费租用
        
        public static void Send(uint tankId, int tankLevel, uint hireTime, uint coinType, uint coinValue, byte vipFreeHire, object className)
        {
            var packet = new RequestHireTank
            {
                TankId = tankId,
                TankLevel = tankLevel,
                HireTime = hireTime,
                CoinType = coinType,
                CoinValue = coinValue,
                VipFreeHire = vipFreeHire
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            TankId = reader.ReadUInt32();
            TankLevel = reader.ReadInt32();
            HireTime = reader.ReadUInt32();
            CoinType = reader.ReadUInt32();
            CoinValue = reader.ReadUInt32();
            VipFreeHire = reader.ReadByte();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(TankId);
            writer.Write(TankLevel);
            writer.Write(HireTime);
            writer.Write(CoinType);
            writer.Write(CoinValue);
            writer.Write(VipFreeHire);
        }
    }
}
