// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.TankMessage
{
    /*
     * client->server 客户端请求使用技能
     */
    public sealed class RequestUseSkill : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_USE_SKILL;
        public short GetMsgType { get { return MsgType; } }
        public uint sceneId;// 战场id
        public ulong targetId;// 选择的目标
        public byte soltNo;// 选择的炮弹
        public short destX;// 攻击目标坐标
        public short destY;
        
        public static void Send(uint sceneId, ulong targetId, byte soltNo, short destX, short destY, object className)
        {
            var packet = new RequestUseSkill
            {
                sceneId = sceneId,
                targetId = targetId,
                soltNo = soltNo,
                destX = destX,
                destY = destY
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            sceneId = reader.ReadUInt32();
            targetId = reader.ReadUInt64();
            soltNo = reader.ReadByte();
            destX = reader.ReadInt16();
            destY = reader.ReadInt16();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(sceneId);
            writer.Write(targetId);
            writer.Write(soltNo);
            writer.Write(destX);
            writer.Write(destY);
        }
    }
}
