// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

using GameProtocol.BulkDataType;
namespace GameProtocol.TankMessage
{
    // 同步坦克信息给TRACK
    public sealed class SyncTankBrief : IProtocol
    {
        public const short MsgType = MessageType.MSG_SYNC_TANK_BRIEF;
        public short GetMsgType { get { return MsgType; } }
        public const int TANK_ADD = 1;
        public const int TANK_DELETE = 2;
        public const int TANK_SKIN_CHANGE = 3;
        public const int TANK_EXIST_TIME_CHANGE = 4;
        public const int TANK_COMMAND_SKILL_CHANGE = 5;//指挥官技能变化
        public uint Oid;// 角色账号ID
        public uint Type;// 同步类型
        public TANK_BRIEF tankBrief;// 坦克简要信息
        
        public static void Send(uint oid, uint type, TANK_BRIEF tankBrief, object className)
        {
            var packet = new SyncTankBrief
            {
                Oid = oid,
                Type = type,
                tankBrief = tankBrief
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            Oid = reader.ReadUInt32();
            Type = reader.ReadUInt32();
            tankBrief = new TANK_BRIEF();
            tankBrief.ReadFromStream(reader);
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(Oid);
            writer.Write(Type);
            tankBrief.WriteToStream(writer);
        }
    }
}
