// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.SystemMessage
{
    /// 服务器系统时间脉冲
    public sealed class SystemTimeImplus : IProtocol
    {
        public const short MsgType = MessageType.MSG_SYSTEM_TIME_IMPLUS;
        public short GetMsgType { get { return MsgType; } }
        public ulong currentTime;
        
        public static void Send(ulong currentTime, object className)
        {
            var packet = new SystemTimeImplus
            {
                currentTime = currentTime
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            currentTime = reader.ReadUInt64();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(currentTime);
        }
    }
}
