// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.SystemMessage
{
    /// 心跳间隔, 单位秒
    public sealed class SystemHeartBeat : IProtocol
    {
        public const short MsgType = MessageType.MSG_SYSTEM_HEARTBEAT;
        public short GetMsgType { get { return MsgType; } }
        public ulong time;
        
        public static void Send(ulong time, object className)
        {
            var packet = new SystemHeartBeat
            {
                time = time
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            time = reader.ReadUInt64();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(time);
        }
    }
}
