// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.ShareTypes
{
    public sealed class CHAT_CHANNEL
    {
        public const int CHANNEL_UNSPECIFIC = 0;
        public const int CHANNEL_PRIVATE = 1<<0;// 密聊频道, 1v1
        public const int CHANNEL_NORMAL = 1<<1;// 普通频道，不在房间里的玩家接收
        public const int CHANNEL_TEAM = 1<<2;// 战队频道, 队友接收
        public const int CHANNEL_ROOM = 1<<3;// 房间频道
        public const int CHANNEL_ROOM_CAMP = 1<<4;// 房间本方阵营频道
        public const int CHANNEL_SCENE = 1<<5;// 战场频道, 场景内可接收
        public const int CHANNEL_SCENE_CAMP = 1<<6;// 战场本方阵营频道
        public const int CHANNEL_WORLD = 1<<7;// 世界频道
        public const int CHANNEL_BUGLE = 1<<8;// 大喇叭频道
        public const int CHANNEL_GM = 1<<9;// GM 频道, GM接收
        public const int CHANNEL_GUILD = 1<<10;// 军团频道
        public const int CHANNEL_GLOBAL = 1<<11;// 跨服频道
        public const int CHANNEL_MASK = 0xFFF;// 频道掩码，同性质频道最大位数
    }
}
