// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.ShareTypes
{
    public sealed class ENUM_CHAT_ERROR
    {
        public const int ECE_UNSPECFIC = 0;// 未定义
        public const int ECE_AUTH_OK = 1;// 认证成功
        public const int ECE_AUTH_INVALID_KEY = 2;// 认证sessionKey错误
        public const int ECE_AUTH_NO_PLAYER = 3;// 认证的玩家未登入
        public const int ECE_PRIVATE_NO_PLAYER = 4;// 密聊对象不存在
        public const int ECE_BEEN_BLOCKED = 5;// 被加入黑名单
        public const int ECE_NORMAL_CHANNEL_LIMIT = 6;// 普通频道30s才能发送一次聊天
        public const int ECE_BAN_CHAT = 7;// 已被禁言
    }
}
