// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.ShareTypes
{
    public sealed class GAME_OBJECT_TYPE
    {
        public const int ZUOBJ_TANK = 0;// 坦克
        public const int ZUOBJ_BULLET = 2;// 炮弹
        public const int ZUOBJ_NPC = 3;// npc
        public const int ZUOBJ_PROPS = 4;// 物品
        public const int ZUOBJ_AINPC = 5;// ai npc
        public const int ZUOBJ_BUFF = 6;// BUFF
        public const int ZUOBJ_FLAG = 7;// 据点
        public const int ZUOBJ_PORTAL = 8;// 传送门
        public const int ZUOBJ_UNKN = 9;// 未知
    }
}
