// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.ShareTypes
{
    public sealed class ROBOT_ENTITY_TYPE
    {
        public const int ENTITY_UNKN = 0;// 未知
        public const int ENTITY_TANK = 1;// 坦克
        public const int ENTITY_BULLET = 2;// 炮弹
        public const int ENTITY_PROP = 3;// 物品
        public const int ENTITY_NPC = 4;// Npc
        public const int ENTITY_BRICK = 5;// 砖块
        public const int ENTITY_BASE = 6;// 基地
        public const int ENTITY_BARBETTE = 7;// 炮塔
        public const int ENTITY_BLOW = 8;// 爆炸类NPC
        public const int ENTITY_REPAIR = 9;// 修理
        public const int ENTITY_ICEWALL = 10;// 冰墙
        public const int ENTITY_AINPC = 11;// AINPC
        public const int ENTITY_AINPC_COMMON = 12;// 普通
        public const int ENTITY_AINPC_GLOBAL_BOSS = 13;// 世界boss
        public const int ENTITY_AINPC_MUTABLE_SUMMON = 14;// 能力根据召唤者自适应的召唤物
        public const int ENTITY_AINPC_MUTABLE_MAP = 15;// 根据地图等级自适应的AINPC
        public const int ENTITY_AINPC_SHADOW = 16;// 分身npc
        public const int ENTITY_AINPC_DEAD_ROUND = 17;// 死亡模式回合触发NPC
        public const int ENTITY_AINPC_TANK = 18;// 坦克AINPC（仅对坦克有效的技能，对这类型有效）
        public const int ENTITY_AINPC_GUILD_BOSS = 19;// 军团BOSS
        public const int ENTITY_MAX = 20;
    }
}
