// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.ShareTypes
{
    public sealed class VAL_TYPE
    {
        public const int VT_NONE = 0;//
        public const int VT_VALUE = 1;// 绝对值
        public const int VT_PERCENT = 2;// 百分比
    }
}
