// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.ShareTypes
{
    /**
     * 位置信息
     */
    public sealed class ZuPosition
    {
        public int sector;
        public float x;
        public float y;
        public float z;
        public void ReadFromStream(BinaryReader reader)
        {
            sector = reader.ReadInt32();
            x = reader.ReadSingle();
            y = reader.ReadSingle();
            z = reader.ReadSingle();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(sector);
            writer.Write(x);
            writer.Write(y);
            writer.Write(z);
        }
    }
}
