// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.StoreMessage
{
    // 请求购买商店物品
    // MSGTYPE_DECLARE(MSG_REQUEST_STORE_PURCHASE),
    public sealed class RequestStorePurchase : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_STORE_PURCHASE;
        public short GetMsgType { get { return MsgType; } }
        public ushort storeType;// 商店类型, 参见STORE_TYPE
        public ushort itemPos;// 商品所在格子的位置
        public ushort count;// 购买数量
        
        public static void Send(ushort storeType, ushort itemPos, ushort count, object className)
        {
            var packet = new RequestStorePurchase
            {
                storeType = storeType,
                itemPos = itemPos,
                count = count
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            storeType = reader.ReadUInt16();
            itemPos = reader.ReadUInt16();
            count = reader.ReadUInt16();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(storeType);
            writer.Write(itemPos);
            writer.Write(count);
        }
    }
}
