// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.BulkDataType
{
    /// Buff信息
    public sealed class BuffInfo
    {
        public uint BuffTpltId;// Buff模板ID
        public ulong BuffInstId;// Buff实例ID
        public byte StackCount;// 叠加层数
        public ulong CasterId;// 释放者id
        public void ReadFromStream(BinaryReader reader)
        {
            BuffTpltId = reader.ReadUInt32();
            BuffInstId = reader.ReadUInt64();
            StackCount = reader.ReadByte();
            CasterId = reader.ReadUInt64();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(BuffTpltId);
            writer.Write(BuffInstId);
            writer.Write(StackCount);
            writer.Write(CasterId);
        }
    }
}
