// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.BulkDataType
{
    // 角色坦克简要信息容器
    public sealed class CHAR_TANK_BRIEF_CONT
    {
        public uint Oid;// 角色OID
        public TANK_BRIEF[] vecTank;// 角色坦克容器
        public void ReadFromStream(BinaryReader reader)
        {
            Oid = reader.ReadUInt32();
            var length2 = reader.ReadUInt16();
            vecTank = new TANK_BRIEF[length2];
            for (var i2 = 0; i2 < length2; i2++)
            {
                vecTank[i2] = new TANK_BRIEF();
                vecTank[i2].ReadFromStream(reader);
            }
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(Oid);
            ushort count2 = (ushort)(vecTank == null ? 0 : vecTank.Length);
            writer.Write(count2);
            for(var i2 = 0; i2 < count2; i2++)
            {
                vecTank[i2].WriteToStream(writer);
            }
        }
    }
}
