// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.BulkDataType
{
    //邀请好礼玩家信息
    public sealed class InviteGiftPlayerInfo
    {
        public string char_uuid;//玩家UUID
        public uint login_cnt;//累计登陆天数
        public uint login_time;//小伙伴登陆时间
        public uint draw_time;//奖励日领取时间
        public uint draw_acc_cnt;//领取累计奖励次数
        public void ReadFromStream(BinaryReader reader)
        {
            char_uuid = reader.ReadString();
            login_cnt = reader.ReadUInt32();
            login_time = reader.ReadUInt32();
            draw_time = reader.ReadUInt32();
            draw_acc_cnt = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(char_uuid);
            writer.Write(login_cnt);
            writer.Write(login_time);
            writer.Write(draw_time);
            writer.Write(draw_acc_cnt);
        }
    }
}
