// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.BulkDataType
{
    /// 对象属性
    public sealed class OBJECT_ATTR
    {
        public CHAR_ATTR base_attr;// 普通对象属性
        public int iBdCtsis;// 建筑穿甲
        public int iBdArmor;// 建筑护甲
        public int iBdAtk;// 建筑攻击力
        public void ReadFromStream(BinaryReader reader)
        {
            base_attr = new CHAR_ATTR();
            base_attr.ReadFromStream(reader);
            iBdCtsis = reader.ReadInt32();
            iBdArmor = reader.ReadInt32();
            iBdAtk = reader.ReadInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            base_attr.WriteToStream(writer);
            writer.Write(iBdCtsis);
            writer.Write(iBdArmor);
            writer.Write(iBdAtk);
        }
    }
}
