// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.BulkDataType
{
    //////////////////////////////////////////////////////////////////////////
    // 战场道具
    public sealed class PropsInfo
    {
        public uint nPropsId;// 技能模板id
        public byte bSlotno;// 位置信息
        public short iCount;// 数量
        public ulong nEndTime;// 技能释放冷却结束时间
        public ulong nCountCoolTime;// 数量刷新冷却时间
        public void ReadFromStream(BinaryReader reader)
        {
            nPropsId = reader.ReadUInt32();
            bSlotno = reader.ReadByte();
            iCount = reader.ReadInt16();
            nEndTime = reader.ReadUInt64();
            nCountCoolTime = reader.ReadUInt64();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(nPropsId);
            writer.Write(bSlotno);
            writer.Write(iCount);
            writer.Write(nEndTime);
            writer.Write(nCountCoolTime);
        }
    }
}
