// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.BulkDataType
{
    /// 匹配信息
    public sealed class PvpPairInfo
    {
        public byte type;// enum PVP_PAIR_POOL_TYPE
        public uint AvgTime;// 匹配平均时间
        public uint Count;// 当前匹配人数
        public void ReadFromStream(BinaryReader reader)
        {
            type = reader.ReadByte();
            AvgTime = reader.ReadUInt32();
            Count = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(type);
            writer.Write(AvgTime);
            writer.Write(Count);
        }
    }
}
