// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.BulkDataType
{
    // 组成信息
    public sealed class SettleGroup
    {
        public int type;
        public int value;
        public void ReadFromStream(BinaryReader reader)
        {
            type = reader.ReadInt32();
            value = reader.ReadInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(type);
            writer.Write(value);
        }
    }
}
