// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.BulkDataType
{
    /// 获得物品
    public sealed class SettleItemInfo
    {
        public uint itemId;
        public int count;
        public void ReadFromStream(BinaryReader reader)
        {
            itemId = reader.ReadUInt32();
            count = reader.ReadInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(itemId);
            writer.Write(count);
        }
    }
}
