// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.BulkDataType
{
    // 天赋格
    public sealed class TALENT_GRID
    {
        public uint nTalentId;// 天赋ID
        public uint nLevel;// 等级
        public void ReadFromStream(BinaryReader reader)
        {
            nTalentId = reader.ReadUInt32();
            nLevel = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(nTalentId);
            writer.Write(nLevel);
        }
    }
}
