// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.MovementMessage
{
    /**
     * 验证位置请求 
     */
    public sealed class RequestValidatePosition : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_VALIDATE_POS;
        public short GetMsgType { get { return MsgType; } }
        public uint oid;// oid
        public ushort x;// 玩家当前坐标
        public ushort y;// 玩家当前坐标
        
        public static void Send(uint oid, ushort x, ushort y, object className)
        {
            var packet = new RequestValidatePosition
            {
                oid = oid,
                x = x,
                y = y
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            oid = reader.ReadUInt32();
            x = reader.ReadUInt16();
            y = reader.ReadUInt16();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(oid);
            writer.Write(x);
            writer.Write(y);
        }
    }
}
