// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.ChatMessage
{
    // ----------------------------------------------------------------------
    ///	@file			protocol/ChatMessage.h
    ///	@brief
    ///	@author			Hou Ming Yuan
    ///	@copyright		Sixcube Information Technology Co,. Ltd. (2012)
    ///	@date			2006-10-19 11:04:55
    // ----------------------------------------------------------------------
    /**
     * 通知客户端聊天相关的错误信息
     * MSGTYPE_DECLARE(MSG_CHAT_ERROR_INFO)
     */
    public sealed class ChatErrorInfo : IProtocol
    {
        public const short MsgType = MessageType.MSG_CHAT_ERROR_INFO;
        public short GetMsgType { get { return MsgType; } }
        public int errNo;// enum ENUM_CHAT_ERROR
        public string errDesc;
        
        public static void Send(int errNo, string errDesc, object className)
        {
            var packet = new ChatErrorInfo
            {
                errNo = errNo,
                errDesc = errDesc
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            errNo = reader.ReadInt32();
            errDesc = reader.ReadString();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(errNo);
            writer.Write(errDesc);
        }
    }
}
