// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

using GameProtocol.ShareTypes;
namespace GameProtocol.ChatMessage
{
    /**
     * 通知聊天服务器相关玩家信息 
     */
    public sealed class NotifyChatPlayerInfo : IProtocol
    {
        public const short MsgType = MessageType.MSG_CHAT_PLAYER_INFO;
        public short GetMsgType { get { return MsgType; } }
        public CHAT_PLAYER_INFO playerInfo;
        
        public static void Send(CHAT_PLAYER_INFO playerInfo, object className)
        {
            var packet = new NotifyChatPlayerInfo
            {
                playerInfo = playerInfo
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            playerInfo = new CHAT_PLAYER_INFO();
            playerInfo.ReadFromStream(reader);
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            playerInfo.WriteToStream(writer);
        }
    }
}
