// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.ClientManageMessage
{
    // ----------------------------------------------------------------------
    ///	@file			protocol/ClientManageMessage.h
    ///	@brief
    ///	@author			Hou Ming Yuan
    ///	@copyright		Sixcube Information Technology Co,. Ltd. (2012)
    ///	@date			2005-3-18 10:14:18
    // ----------------------------------------------------------------------
    /// @addtogroup dt_ManageMessage
    /// @{
    public sealed class ConnectIndicatePacket : IProtocol
    {
        public const short MsgType = MessageType.MSG_CLIENT_MANAGE_CONNECT_INDICATE;
        public short GetMsgType { get { return MsgType; } }
        public uint ip;
        public uint isOut;///- 是否是服务端主动向外的连接
        
        public static void Send(uint ip, uint isOut, object className)
        {
            var packet = new ConnectIndicatePacket
            {
                ip = ip,
                isOut = isOut
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            ip = reader.ReadUInt32();
            isOut = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(ip);
            writer.Write(isOut);
        }
    }
}
