// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.MonitorMessage
{
    public sealed class MANAGE_COMMAND
    {
        public const int MCMD_UNKNOWN = 0;
        public const int MCMD_START = 1;// 启动
        public const int MCMD_STOP = 2;// 停止
        public const int MCMD_RESTART = 3;// 重启
        public const int MCMD_REFRESH = 4;// 刷新
        public const int MCMD_PING = 5;// 心跳
    }
}
