// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.VipMessage
{
    public sealed class ChargeBillsBakInfo
    {
        public uint drawTime;//领取时间
        public uint coinCount;//获得点券数
        public void ReadFromStream(BinaryReader reader)
        {
            drawTime = reader.ReadUInt32();
            coinCount = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(drawTime);
            writer.Write(coinCount);
        }
    }
}
