// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CharMessage
{
    /*
     * Server->Client：允许选择角色进入游戏
     */
    public sealed class CharPickApprovedMessage : IProtocol
    {
        public const short MsgType = MessageType.MSG_CHAR_PICKAPPROVED;
        public short GetMsgType { get { return MsgType; } }
        public string charUuid;
        
        public static void Send(string charUuid, object className)
        {
            var packet = new CharPickApprovedMessage
            {
                charUuid = charUuid
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            charUuid = reader.ReadString();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(charUuid);
        }
    }
}
