// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CharMessage
{
    /*
     * Server->Client：拒绝角色进入游戏。
     */
    public sealed class CharPickRejectedMessage : IProtocol
    {
        public const short MsgType = MessageType.MSG_CHAR_PICKREJECTED;
        public short GetMsgType { get { return MsgType; } }
        public const int PRR_DOLOAD_FAILED = 1;// 加载角色数据失败
        public byte Reason;
        
        public static void Send(byte reason, object className)
        {
            var packet = new CharPickRejectedMessage
            {
                Reason = reason
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            Reason = reader.ReadByte();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(Reason);
        }
    }
}
