// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.CharMessage
{
    public sealed class CLIENT_STAT_TYPE
    {
        public const int CSTAT_SCREEN = 1;// 采集屏幕分辨率
        public const int CSTAT_LOADED = 2;// 加载时间
        public const int CSTAT_FRMRATE = 4;// 掉帧统计
        public const int CSTAT_SELMODE = 5;// 自主模式选择
    }
}
