// Generated by proto_to_csharp.py. DO NOT EDIT!
namespace GameProtocol.CharMessage
{
    public sealed class FUNC_NOTIFY_UI_TYPE
    {
        public const int FNUT_UNKNOW = 0;//未知
        public const int FNUT_TANK_MAKE = 1;//坦克制造界面
        public const int FNUT_ROLL_LUCK = 2;//幸运转盘界面
        public const int FNUT_ROLL_SLOT_MACHINE = 3;//神秘球转盘界面
        public const int FNUT_ROLL_DRAGON_BOAT = 4;//龙舟转盘界面
        public const int FNUT_ROLL_ONLINE_PEAK = 5;//峰值在线转盘界面
        public const int FNUT_ROLL_ANNIVERSARY = 6;//周年庆转盘界面
        public const int FNUT_CLOUD_PURCHASE = 7;//云购界面
        public const int FNUT_BONFIRE = 8;//篝火界面
        public const int FNUT_TREASURE = 9;//一元夺宝
    }
}
