// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CharMessage
{
    public sealed class GmopChangeCharHonor : IProtocol
    {
        public const short MsgType = MessageType.MSG_GATE_CHANGE_CHAR_HONOR;
        public short GetMsgType { get { return MsgType; } }
        public ChangeHonorInfo info;
        
        public static void Send(ChangeHonorInfo info, object className)
        {
            var packet = new GmopChangeCharHonor
            {
                info = info
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            info = new ChangeHonorInfo();
            info.ReadFromStream(reader);
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            info.WriteToStream(writer);
        }
    }
}
