// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CharMessage
{
    // 通知金币领取结果
    public sealed class NotifyDrawGoldenPoolResult : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_DRAW_GOLDEN_POOL_RESULT;
        public short GetMsgType { get { return MsgType; } }
        public const int DGPR_OK = 0;/// 领取成功
        public const int DGPR_ERROR_NONE = 10;/// 领取失败
        public const int DGPR_ERROR_NO_GOLDEN = 11;/// 领取失败，池内没有金币
        public const int DGPR_ERROR_NOT_VIP = 12;/// 领取失败，不是VIP
        public uint Result;///领取结果
        public uint Count;///领取的金币个数
        
        public static void Send(uint result, uint count, object className)
        {
            var packet = new NotifyDrawGoldenPoolResult
            {
                Result = result,
                Count = count
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            Result = reader.ReadUInt32();
            Count = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(Result);
            writer.Write(Count);
        }
    }
}
