// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CharMessage
{
    /// 通知领取军团礼包的最后时间
    public sealed class NotifyGuildGiftTime : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_GUILD_GIFT_TIME;
        public short GetMsgType { get { return MsgType; } }
        public uint Time;// 时间
        
        public static void Send(uint time, object className)
        {
            var packet = new NotifyGuildGiftTime
            {
                Time = time
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            Time = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(Time);
        }
    }
}
