// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CharMessage
{
    // 更新角色经验 gatesvr->client
    public sealed class NotifyCharExp : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_CHAR_EXP;
        public short GetMsgType { get { return MsgType; } }
        public uint Exp;// 经验值
        public int AddExp;// 获得的经验值
        public byte type;// enum LEVEL_TYPE
        
        public static void Send(uint exp, int addExp, byte type, object className)
        {
            var packet = new NotifyCharExp
            {
                Exp = exp,
                AddExp = addExp,
                type = type
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            Exp = reader.ReadUInt32();
            AddExp = reader.ReadInt32();
            type = reader.ReadByte();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(Exp);
            writer.Write(AddExp);
            writer.Write(type);
        }
    }
}
