// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CharMessage
{
    /// 通知是否已经进行首充
    public sealed class NotifyFirstCharge : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_FIRST_CHARGE;
        public short GetMsgType { get { return MsgType; } }
        public uint ChargeCount;// 1:标识首充数额
        public uint Rate;// 2:返礼券的倍率（100代表1倍）
        public uint Min;// 3:最低的返还礼券额度
        public uint Max;// 4:最高的返还礼券额度
        
        public static void Send(uint chargeCount, uint rate, uint min, uint max, object className)
        {
            var packet = new NotifyFirstCharge
            {
                ChargeCount = chargeCount,
                Rate = rate,
                Min = min,
                Max = max
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            ChargeCount = reader.ReadUInt32();
            Rate = reader.ReadUInt32();
            Min = reader.ReadUInt32();
            Max = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(ChargeCount);
            writer.Write(Rate);
            writer.Write(Min);
            writer.Write(Max);
        }
    }
}
