// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CharMessage
{
    // 通知使用avatar
    public sealed class NotifyUseAvatar : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_USE_AVATAR;
        public short GetMsgType { get { return MsgType; } }
        public uint avatarId;
        
        public static void Send(uint avatarId, object className)
        {
            var packet = new NotifyUseAvatar
            {
                avatarId = avatarId
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            avatarId = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(avatarId);
        }
    }
}
