// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CharMessage
{
    /// 通知角色的2级密保信息
    public sealed class NotifyCharProtectInfo : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_CHAR_PROTECT_PWD;
        public short GetMsgType { get { return MsgType; } }
        public byte HasPwd;///是否设定了2级密保
        public uint DelPwdTicket;///密保失效的时间点 （0表示一直有效，该值若非0则一定是指向未来的时间点）
        
        public static void Send(byte hasPwd, uint delPwdTicket, object className)
        {
            var packet = new NotifyCharProtectInfo
            {
                HasPwd = hasPwd,
                DelPwdTicket = delPwdTicket
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            HasPwd = reader.ReadByte();
            DelPwdTicket = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(HasPwd);
            writer.Write(DelPwdTicket);
        }
    }
}
