// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CharMessage
{
    //通知附身玩家Gate信息
    public sealed class NotifyObserverPlayerGateMessage : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_OBSERVER_PLAYER_GATE;
        public short GetMsgType { get { return MsgType; } }
        public string gate_realm;//网关域名
        public uint gate_port;//网关端口
        public uint target_client_id;//附身目标ClientID
        
        public static void Send(string gate_realm, uint gate_port, uint target_client_id, object className)
        {
            var packet = new NotifyObserverPlayerGateMessage
            {
                gate_realm = gate_realm,
                gate_port = gate_port,
                target_client_id = target_client_id
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            gate_realm = reader.ReadString();
            gate_port = reader.ReadUInt32();
            target_client_id = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(gate_realm);
            writer.Write(gate_port);
            writer.Write(target_client_id);
        }
    }
}
