// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CharMessage
{
    // MSGTYPE_DECLARE(MSG_NOTIFY_AFK_STATUS)
    // game -> gate -> client
    public sealed class NotifyAfkStatus : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_AFK_STATUS;
        public short GetMsgType { get { return MsgType; } }
        public uint State;// 0 警告, 1 表示挂机成立
        
        public static void Send(uint state, object className)
        {
            var packet = new NotifyAfkStatus
            {
                State = state
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            State = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(State);
        }
    }
}
