// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

using GameProtocol.BulkDataType;
namespace GameProtocol.CharMessage
{
    /// 通知副本记录
    public sealed class OnePveRecord
    {
        public uint mapId;// 地图id
        public uint PassTime;// 通关时间点
        public uint UseTime;// 通关所用的时间(秒)
        public RECORD_BRIEF[] charVec;// 玩家列表
        public void ReadFromStream(BinaryReader reader)
        {
            mapId = reader.ReadUInt32();
            PassTime = reader.ReadUInt32();
            UseTime = reader.ReadUInt32();
            var length4 = reader.ReadUInt16();
            charVec = new RECORD_BRIEF[length4];
            for (var i4 = 0; i4 < length4; i4++)
            {
                charVec[i4] = new RECORD_BRIEF();
                charVec[i4].ReadFromStream(reader);
            }
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(mapId);
            writer.Write(PassTime);
            writer.Write(UseTime);
            ushort count4 = (ushort)(charVec == null ? 0 : charVec.Length);
            writer.Write(count4);
            for(var i4 = 0; i4 < count4; i4++)
            {
                charVec[i4].WriteToStream(writer);
            }
        }
    }
}
