// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CharMessage
{
    /// 请求保存系统设置
    public sealed class RequestChangeSetting : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_CHANGE_SETTING;
        public short GetMsgType { get { return MsgType; } }
        public uint setting;// enum CHAR_SETTING_FLAG_BIT
        
        public static void Send(uint setting, object className)
        {
            var packet = new RequestChangeSetting
            {
                setting = setting
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            setting = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(setting);
        }
    }
}
