// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CharMessage
{
    /// MSGTYPE_DECLARE(MSG_REQUEST_LEARN_GUILD_SKILL)		     // 角色请求学习军团技能
    public sealed class RequestLearnGuildSkill : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_LEARN_GUILD_SKILL;
        public short GetMsgType { get { return MsgType; } }
        public uint GuildSkillId;// 军团技能ID
        
        public static void Send(uint guildSkillId, object className)
        {
            var packet = new RequestLearnGuildSkill
            {
                GuildSkillId = guildSkillId
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            GuildSkillId = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(GuildSkillId);
        }
    }
}
