// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

using GameProtocol.TradeMessage;
namespace GameProtocol.CharMessage
{
    // 请求购买体力
    public sealed class RequestBuyThew : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_BUY_THEW;
        public short GetMsgType { get { return MsgType; } }
        public GoodsCoinVal[] coinVec;// 使用的货币
        
        public static void Send(GoodsCoinVal[] coinVec, object className)
        {
            var packet = new RequestBuyThew
            {
                coinVec = coinVec
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            var length1 = reader.ReadUInt16();
            coinVec = new GoodsCoinVal[length1];
            for (var i1 = 0; i1 < length1; i1++)
            {
                coinVec[i1] = new GoodsCoinVal();
                coinVec[i1].ReadFromStream(reader);
            }
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            ushort count1 = (ushort)(coinVec == null ? 0 : coinVec.Length);
            writer.Write(count1);
            for(var i1 = 0; i1 < count1; i1++)
            {
                coinVec[i1].WriteToStream(writer);
            }
        }
    }
}
