// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CharMessage
{
    /// 请求领取累计签到奖励
    public sealed class RequestSignInStageAward : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_STAGE_SIGN_IN_AWARD;
        public short GetMsgType { get { return MsgType; } }
        public uint Stage;// 请求领取的阶段
        
        public static void Send(uint stage, object className)
        {
            var packet = new RequestSignInStageAward
            {
                Stage = stage
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            Stage = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(Stage);
        }
    }
}
