// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CharMessage
{
    // MSGTYPE_DECLARE(MSG_REQUEST_BUDDY_BRIEF),
    // 主动请求brief信息
    public sealed class RequestBuddyBrief : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_BUDDY_BRIEF;
        public short GetMsgType { get { return MsgType; } }
        public uint[] charIdVec;// 需要查找的brief信息的角色
        
        public static void Send(uint[] charIdVec, object className)
        {
            var packet = new RequestBuddyBrief
            {
                charIdVec = charIdVec
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            var length1 = reader.ReadUInt16();
            charIdVec = new uint[length1];
            for (var i1 = 0; i1 < length1; i1++)
            {
                charIdVec[i1] = reader.ReadUInt32();
            }
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            ushort count1 = (ushort)(charIdVec == null ? 0 : charIdVec.Length);
            writer.Write(count1);
            for(var i1 = 0; i1 < count1; i1++)
            {
                writer.Write(charIdVec[i1]);
            }
        }
    }
}
