// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CharMessage
{
    public sealed class SlotMachineChar
    {
        public string strName;// 玩家名称
        public uint RlteCount;// 转球次数
        public uint Rank;// 排名
        public string strUuid;// 玩家UUID
        public void ReadFromStream(BinaryReader reader)
        {
            strName = reader.ReadString();
            RlteCount = reader.ReadUInt32();
            Rank = reader.ReadUInt32();
            strUuid = reader.ReadString();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(strName);
            writer.Write(RlteCount);
            writer.Write(Rank);
            writer.Write(strUuid);
        }
    }
}
