// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CharMessage
{
    // gate->game 同步角色信息给gamesvr
    public sealed class SyncInfoToGame : IProtocol
    {
        public const short MsgType = MessageType.MSG_SYNC_CHAR_INFO_TOGAME;
        public short GetMsgType { get { return MsgType; } }
        public uint SceneId;
        public uint charOid;
        public byte vipLevel;// vip等级
        
        public static void Send(uint sceneId, uint charOid, byte vipLevel, object className)
        {
            var packet = new SyncInfoToGame
            {
                SceneId = sceneId,
                charOid = charOid,
                vipLevel = vipLevel
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            SceneId = reader.ReadUInt32();
            charOid = reader.ReadUInt32();
            vipLevel = reader.ReadByte();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(SceneId);
            writer.Write(charOid);
            writer.Write(vipLevel);
        }
    }
}
