// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CharMessage
{
    // MSGTYPE_DECLARE(MSG_SYNC_CHAR_NAME),
    // gate->track 同步角色改名信息给tracksvr
    public sealed class SyncCharChangeName : IProtocol
    {
        public const short MsgType = MessageType.MSG_SYNC_CHAR_NAME;
        public short GetMsgType { get { return MsgType; } }
        public uint acctOid;// 帐号OID
        public string charUuid;// 角色的UID
        public string newName;// 修改后的名字
        
        public static void Send(uint acctOid, string charUuid, string newName, object className)
        {
            var packet = new SyncCharChangeName
            {
                acctOid = acctOid,
                charUuid = charUuid,
                newName = newName
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            acctOid = reader.ReadUInt32();
            charUuid = reader.ReadString();
            newName = reader.ReadString();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(acctOid);
            writer.Write(charUuid);
            writer.Write(newName);
        }
    }
}
