// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.AuthMessage
{
    /**
     * 打断正在离开游戏的请求  
     * MSGTYPE_DECLARE(MSG_AUTH_REQUEST_CANCEL_LOGOUT)
     */
    public sealed class AuthRequestCancleLogout : IProtocol
    {
        public const short MsgType = MessageType.MSG_AUTH_REQUEST_CANCEL_LOGOUT;
        public short GetMsgType { get { return MsgType; } }
        public uint session;
        
        public static void Send(uint session, object className)
        {
            var packet = new AuthRequestCancleLogout
            {
                session = session
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            session = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(session);
        }
    }
}
