// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.AuthMessage
{
    /**
     *  向认证服务器请求登录到区服网关
     *
     *　MSG_AUTH_REQUEST_REGION_SESSION
     */
    public sealed class RequestRegionSession : IProtocol
    {
        public const short MsgType = MessageType.MSG_AUTH_REQUEST_REGION_SESSION;
        public short GetMsgType { get { return MsgType; } }
        public ushort region_id;// 区服ID
        public uint session;// 所用的SessionKey
        public string login;// 所用的登录名
        
        public static void Send(ushort region_id, uint session, string login, object className)
        {
            var packet = new RequestRegionSession
            {
                region_id = region_id,
                session = session,
                login = login
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            region_id = reader.ReadUInt16();
            session = reader.ReadUInt32();
            login = reader.ReadString();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(region_id);
            writer.Write(session);
            writer.Write(login);
        }
    }
}
