// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.AuthMessage
{
    /**
     * 版本验证失败 
     */
    public sealed class VersionFail : IProtocol
    {
        public const short MsgType = MessageType.MSG_AUTH_VESION_FAILED;
        public short GetMsgType { get { return MsgType; } }
        public int reason;
        
        public static void Send(int reason, object className)
        {
            var packet = new VersionFail
            {
                reason = reason
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            reason = reader.ReadInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(reason);
        }
    }
}
