// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.QuestMessage
{
    // 通知完成任务
    public sealed class NotifyCompleteQuest : IProtocol
    {
        public const short MsgType = MessageType.MSG_NOTIFY_COMPLETE_QUEST;
        public short GetMsgType { get { return MsgType; } }
        public uint questId;
        
        public static void Send(uint questId, object className)
        {
            var packet = new NotifyCompleteQuest
            {
                questId = questId
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            questId = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(questId);
        }
    }
}
