// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.QuestMessage
{
    // 请求切换任务
    public sealed class RequestSwitchQuest : IProtocol
    {
        public const short MsgType = MessageType.MSG_REQUEST_SWITCH_QUEST;
        public short GetMsgType { get { return MsgType; } }
        public uint QuestId;
        
        public static void Send(uint questId, object className)
        {
            var packet = new RequestSwitchQuest
            {
                QuestId = questId
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            QuestId = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(QuestId);
        }
    }
}
