// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.ClusterDataType
{
    // ----------------------------------------------------------------------
    ///	@file			protocol/ClusterDataType.h
    ///	@brief
    ///	@author			Bob Lee (bob@onwind.cn)
    ///	@copyright		Sixcube Information Technology Co,. Ltd. (2012)
    ///	@date			2006-4-16 15:23:14
    // ----------------------------------------------------------------------
    /// @addtogroup dt_ClusterMessage
    /// @{
    /**
     * 认证事件 
     */
    // 角色登入
    // 角色登出
    // 服务器列表更新
    // 认证会话请求(Gate用)
    // 认证关闭请求(Gate用)
    // 排队信息更新
    /**
     * 认证注册结果 
     */
    //位置状态
    //注册成功
    //UID已经注册过
    //REGION不存在
    //REGION存在，但节点不在REGION计划中
    /**
     * 服务节点内型 
     */
    //未知类型
    //网关服务器
    //聊天服务器
    //认证前端服务器
    //认证中心服务器
    //管理用客户端
    /**
     * 世界状态 
     */
    //Realm刚被创建，绑定到SESSION
    //已经发送SESSION请求
    //SESSION请求在排队中
    //已经登陆到对应的游戏世界
    /// 表示登陆到系统中的一个用户登陆信息
    public sealed class GAME_SESSION
    {
        public uint nAcctId;// 账号id
        public int session;// Session
        public uint client_id;// 在Gate上的连接号
        public void ReadFromStream(BinaryReader reader)
        {
            nAcctId = reader.ReadUInt32();
            session = reader.ReadInt32();
            client_id = reader.ReadUInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(nAcctId);
            writer.Write(session);
            writer.Write(client_id);
        }
    }
}
