// Generated by proto_to_csharp.py. DO NOT EDIT!
using System.IO;

namespace GameProtocol.CurrencyMessage
{
    /// 请求进行RMB兑换
    /// Client -> Server
    public sealed class RequestRmbTranser : IProtocol
    {
        public const short MsgType = MessageType.MSG_CHAR_CURRENCY_REQUEST_RMB_TRANSER;
        public short GetMsgType { get { return MsgType; } }
        public int amount;// 额度
        
        public static void Send(int amount, object className)
        {
            var packet = new RequestRmbTranser
            {
                amount = amount
            };
            NetMessage.Send(packet.BuildPacket(), className);
        }
        
        public byte[] BuildPacket()
        {
            var buffer = ProtocolBuffer.Writer;
            buffer.Write(MsgType);
            buffer.Write(ProtocolBuffer.Zero);
            WriteToStream(buffer);
            return ProtocolBuffer.CacheStream.ToArray();
        }
        
        public void ReadFromStream(BinaryReader reader)
        {
            amount = reader.ReadInt32();
        }
        
        public void WriteToStream(BinaryWriter writer)
        {
            writer.Write(amount);
        }
    }
}
